In [115]:
# ! pip install calitp_data_analysis

In [116]:
%%capture

import warnings
warnings.filterwarnings('ignore')

import calitp_data_analysis.magics

In [117]:
# import shared_utils

In [118]:
import gcsfs as fs
import geopandas as gpd
import numpy as np
import pandas as pd
from calitp_data_analysis import get_fs, utils
from calitp_data_analysis.sql import to_snakecase
# from siuba import *

fs = get_fs()

In [119]:
import altair as alt
import folium
import matplotlib

In [120]:
# alt.data_transformers.enable("vegafusion")

In [121]:
# ## run this for maps to show
# ! pip install folium matplotlib mapclassify

In [122]:
#### ! pip install vegafusion
#### ! pip install "vegafusion[embed]>=1.5.0"
##### ! pip install --upgrade "vegafusion[embed]>=1.5.0" "vegafusion>=1.5.0"

In [123]:
import _replica_utils

In [124]:
from IPython.display import HTML

In [125]:
from calitp_data_analysis import calitp_color_palette as cp

In [126]:
pd.set_option("display.max_columns", None)

In [127]:
gcs_path = "gs://calitp-analytics-data/data-analyses/big_data/STM/"

In [128]:
blk_grp_url = "CA_Census_blocks_w_Cities_centered.zip"

In [129]:
display(HTML("<h1>Origin-Destination Big Data Analysis: Southern California POIs</h1>"))

In [130]:
display(HTML("This analysis uses Replica Data to identify the top trip start points within a a group of Caltrans Districts and determine what types of trips are occuring when and where."))

In [131]:
# shape_data_name = "origins/replica-stm_origin_la-03_19_26-origin_layer.zip"

# origins_name = "replica-stm_origin_la-03_18_26-trips_dataset.zip"


shape_data_name = "origins/California_hex7_layer.zip"
origins_name = "D7_8_11_12_replica-stm_regional_travel-06_25_26-trips_dataset.zip"

In [132]:
from calitp_data_analysis import utils

In [133]:
with get_fs().open(f"{gcs_path}{shape_data_name}") as f:
        shps = to_snakecase(gpd.read_file(f))

In [134]:
len(shps)

34623

In [135]:
shps.sample()

,name,id,centrlat,centrlon,sqmi,origin,orig_sqmi,geometry
22530,8729a96c8ffffff,608718872056430600,37.2315,-120.8139,2.1136,6,2.8387,"POLYGON ((-120.80524 37.22075, -120.82164 37.2..."

In [136]:
# shps.explore(column="geoname", tooltip=['geoname', 'customgeo', 'centrlat', 'centrlon', 'sqmi', 'origin',
#        'orig_sqmi'])

In [137]:
df = to_snakecase( pd.read_csv(f"{gcs_path}{origins_name}"))

In [138]:
df.sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng
89522,11370796333181706196,"1 (Tract 7018.01, Los Angeles, CA)","7018.01 (Los Angeles, CA)","Los Angeles County, CA",California,"2 (Tract 111.01, San Luis Obispo, CA)","111.01 (San Luis Obispo, CA)","San Luis Obispo County, CA",California,auto_passenger,shop,work,15:25:00,18:51:39,206,180.0,unknown_vehicle_type,unknown_fuel_type,NaN,NaN,NaN,retail,retail,retail,retail,6021754424632516429,2264791297239782980,43.0,female,white_not_hispanic_or_latino,employed,in_person,80916.0,auto_passenger,2,182364.0,two,core,naics52,single_family,not_attending_school,some_college,owner,english,"1 (Tract 9200.13, Los Angeles, CA)","9200.13 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 7018.01, Los Angeles, CA)","7018.01 (Los Angeles, CA)","Los Angeles County, CA",California,8729a1981ffffff,8729adc46ffffff,608718333994336300,60377018011,-118.4622,34.0247,060790111012,6.087192e+17,35.2724,-120.6581

columns `origin_custom` & `destination_custom` are for the hex cells, geoname is lost when uploading to Replica to add to the data. check with reps.

In [139]:
# df.destination_custom_id.nunique()

In [140]:
# df.origin_custom_id.sample()

In [141]:
# df.destination_custom_id.sample()

In [142]:
# shps[shps['id']==608718594158624800]

In [143]:
### add in geometry column using the hex cells

In [144]:
df_origins, df_dests = _replica_utils.prep_replica_data_w_shp(df, shape_data_name, 'origin_custom_id', 'destination_custom_id')

In [145]:
# df_origins

In [146]:
# df.origin_custom_id.value_counts()

In [147]:
# df.origin_bgrp_2020.value_counts()

In [148]:
#### add in blockgroups to get the city name- another easier way to identify and group instead of a hex cell number

In [149]:
df_origins = _replica_utils.add_city_from_blkgrps(df_origins, "origin_cty_2020", "origin_trct_2020", "origin_bgrp_2020", "destination_cty_2020", "destination_trct_2020", "destination_bgrp_2020")

In [150]:
df_dests = _replica_utils.add_city_from_blkgrps(df_dests, "origin_cty_2020", "origin_trct_2020", "origin_bgrp_2020", "destination_cty_2020", "destination_trct_2020", "destination_bgrp_2020")

In [151]:
# df_origins.head()

In [152]:
# df_dests.head()

In [153]:
# (df_origins.sample(50)).explore(column="origin_custom_id")

In [154]:
display(HTML("<h2><strong>Trip Counts</strong></h2>"))

In [155]:
assert df_origins.origin_custom_id.nunique() == 50

In [156]:
display(HTML(f"The number of trips Traveling <strong>From</strong> the top 50 locations is <strong>{len(df_origins)}</strong>"))

In [157]:
display(HTML(f"<strong>Where trips are Originating</strong>"))

In [243]:
df_origins_city = (df_origins.origin_city.value_counts().reset_index()).rename(columns={"origin_city":"Origin City", "count":"Number of Trips"})

In [244]:
alt.Chart(df_origins_city).mark_bar().encode(
    x=alt.X("Origin City:O", title = "Trip Origin City"),
    y=alt.Y("Number of Trips:Q", title="Total Number of Trips"),
    color=alt.Color("Origin City:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    tooltip = ['Origin City', 'Number of Trips']
    ).properties(
    width=800,  
    height=300,
    title='Number of Trips by City')

alt.Chart(...)

In [245]:
# df_origins_city = (df_origins.origin_custom.value_counts().reset_index()).rename(columns={"origin_city":"Origin Hex Cell", "count":"Number of Trips"})

In [246]:
# df_origins.sample()

In [247]:
df_origins_city

                              Origin City  Number of Trips
0         Los Angeles, Los Angeles County            86837
1             San Diego, San Diego County            24112
2      Unincorporated, Los Angeles County            10958
3        Santa Monica, Los Angeles County             9206
4          Long Beach, Los Angeles County             8613
5                Blythe, Riverside County             8322
6          Palm Springs, Riverside County             7050
7                 Indio, Riverside County             5179
8             Burbank, Los Angeles County             4771
9          Ontario, San Bernardino County             4296
10                 Anaheim, Orange County             4233
11     West Hollywood, Los Angeles County             4149
12           Newport Beach, Orange County             3931
13         El Segundo, Los Angeles County             3749
14            La Quinta, Riverside County             3051
15      Beverly Hills, Los Angeles County             2759
16           Pasadena, Los Angeles County             2412
17  Unincorporated, San Bernardino County             2331
18          Unincorporated, Orange County             2284
19   Big Bear Lake, San Bernardino County             2276
20             Coronado, San Diego County              522
21            Coachella, Riverside County              209
22              Costa Mesa, Orange County              142
23  Rancho Santa Margarita, Orange County              118
24        Culver City, Los Angeles County               18
25        Signal Hill, Los Angeles County               17
26          Inglewood, Los Angeles County                3
27       Unincorporated, Riverside County                1

In [159]:
unique_origin_list = df_origins.origin_city.unique().tolist()

In [160]:
# unique_origin_list

In [161]:
summary = _replica_utils.return_score_summary_single_df(df_origins, unique_origin_list, "origin_geometry", "origin_city")

In [162]:
# summary.sample()

In [163]:
summary.columns = [col.replace('_', ' ').title() for col in summary.columns]

In [164]:
# df_origins.sample()

In [165]:
summary_melt =  pd.melt(
        summary,
        id_vars=["Trip Grouping"],
        value_vars=['Trip Grouping', 'Total Trips',
                    'N Auto Trips', 'Pct Auto Trips',
                    'N Tranist Trips', 'Pct Transit Trips',
                    'N Walking Trips', 'Pct Walking Trips',
                    'Auto Mean Minutes', 'Auto Median Minutes', 'Auto Max Minutes',
                    'Auto Mean Miles','Auto Median Miles', 'Auto Max Miles',
                    'Transit Mean Minutes','Transit Median Minutes', 'Transit Max Minutes',
                    'Transit Mean Miles','Transit Median Miles', 'Transit Max Miles',
                    'Walking Mean Minutes', 'Walking Median Minutes', 'Walking Max Minutes',
                    'Walking Mean Miles','Walking Median Miles', 'Walking Max Miles',
                   ],
        var_name="Metric",  # New column for original measurement names
        # value_name="_Value"
)

In [166]:
display(HTML("<h2><strong>Trip Type Summaries</strong></h2>"))

In [167]:
list_of_dfs = []


for origin in unique_origin_list:
    origins_subset = df_origins[df_origins["origin_city"] == origin]

    modes_breakdown_subset = _replica_utils.get_mode_split(origins_subset, "origin_city")

    list_of_dfs.append(modes_breakdown_subset)

modes_breakdown = pd.concat(list_of_dfs, ignore_index=True)

In [168]:
modes_breakdown.columns = [col.replace('_', ' ').title() for col in modes_breakdown.columns]

In [169]:
modes_breakdown.Mode.value_counts()

Mode
other_travel_mode    28
private_auto         27
auto_passenger       25
public_transit       23
biking               19
commercial           17
walking              14
on_demand_auto       11
Name: count, dtype: int64

In [170]:
# len(modes_breakdown)

In [171]:
# (modes_breakdown[modes_breakdown["Mode"]=="walking"]).sort_values('Pct Trips')

In [172]:
# (df_origins[df_origins["origin_custom_id"]==608718595349807100]).sample()

In [173]:
alt.Chart(modes_breakdown).mark_bar().encode(
    x=alt.X("Trip Grouping:O", title = "Trip Origin"),
    y=alt.Y("Total Trips:Q", title="Total Number of Trips"),
    color=alt.Color("Mode:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    tooltip = ['Total Trips', 'Mode']
    ).properties(
    width=800,  
    height=300,
    title='Modes by Trip Type')

alt.Chart(...)

In [231]:
# df_origins.sample()

In [230]:
# df_origins.groupby('origin_city')['origin_bgrp_2020'].nunique()

In [176]:
# (modes_breakdown[modes_breakdown['Mode']=="walking"]).sort_values('Total Trips')

In [177]:
## check the highest walking 
# (df_origins[df_origins['origin_custom_id']==608718595349807100]).explore()

In [178]:
# alt.Chart(modes_breakdown).mark_bar().encode(
#     x=alt.X('Trip Grouping:O', title ="Trip Origin"),
#     y= alt.Y('Pct Trips:Q', title="Pct of Total Trips"),
#     color=alt.Color('Trip Grouping:N', scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS), legend=alt.Legend(title='Trip Grouping')),
#     column= alt.Column('Mode:N', title="Mode"),
#     tooltip=['Pct Trips', 'Mode', 'Trip Grouping']
# ).properties(width = 100, height = 400, title = "Modes by Trip Type")

In [179]:
display(HTML("<h3><strong>Closer Look at Auto, Transit & Walking Trips</strong></h3>"))

In [180]:
display(HTML("<strong>Tip:</strong> Use the dropdown menu to select different metrics to see on the chart."))

In [181]:
metrics_list = summary_melt["Metric"].unique().tolist()

metrics_dropdown = alt.binding_select(
        options=metrics_list,
        name="Metrics: ",
    )
    # Column that controls the bar charts
xcol_param = alt.selection_point(
        fields=["Metric"], value=metrics_list[0], bind=metrics_dropdown
    )

chart = (alt.Chart(summary_melt, title="Metric by Trip Types")
        .mark_bar()
        .encode(
            x=alt.X("value"),
            y=alt.Y("Trip Grouping"),
            color=alt.Color("Trip Grouping",
                                  scale=alt.Scale(
                                      range=cp.CALITP_CATEGORY_BRIGHT_COLORS))
        ).properties(width=400, height=350)
    ).add_params(xcol_param).transform_filter(xcol_param)

display(HTML("""
<style>
form.vega-bindings {
  position: absolute;
  left: 0px;
  top: -0px;
}
</style>
"""))

(chart)

alt.Chart(...)

In [182]:
display(HTML("<br>"
            "<br>"))

In [183]:
summary_long_all_miles = pd.melt(
    summary,
    id_vars=["Trip Grouping"],
    value_vars=[
        'Auto Mean Miles', 'Auto Median Miles', 'Auto Max Miles', 
        'Transit Mean Miles', 'Transit Median Miles', 'Transit Max Miles',
        'Walking Mean Miles', 'Walking Median Miles', 'Walking Max Miles'],
        var_name="Metric",  # New column for original measurement names
        value_name="Miles")

In [184]:
summary_long_all_min = pd.melt(
    summary,
    id_vars=["Trip Grouping"],
    value_vars=[
        'Auto Mean Minutes', 'Auto Median Minutes', 'Auto Max Minutes',
        'Transit Mean Minutes', 'Transit Median Minutes', 'Transit Max Minutes',
        'Walking Mean Minutes', 'Walking Median Minutes', 'Walking Max Minutes'],
        var_name="Metric",  # New column for original measurement names
        value_name="Mintues")

In [185]:
display(HTML("<h3><strong>Trip Length</strong></h3>"))

In [186]:
alt.Chart(summary_long_all_min).mark_bar().encode(
    x="Mintues:Q",
    y="Metric:O",
    color=alt.Color("Metric:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    # row="Trip Grouping:O",
    facet=alt.Facet('Trip Grouping:O').columns(4),
).properties(title="Travel Length by Trip Type & Mode")

alt.Chart(...)

In [187]:
alt.Chart(summary_long_all_miles).mark_bar().encode(
    x="Miles:Q",
    y="Metric:O",
    color=alt.Color("Metric:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    # row="Trip Grouping:O",
    facet=alt.Facet('Trip Grouping:O').columns(4),
).properties(title="Travel Distance by Trip Type & Mode")

alt.Chart(...)

In [188]:
display(HTML("<h3><strong>Trip Timing</strong></h3>"))

In [189]:
display(HTML("<strong>Tip:</strong> You can zoom into each graph to better see the timing of the trips by mode"))

In [190]:
import datetime

In [191]:
def add_hour_summary_by_mode(df, grouping_col, grouping_list, mode_col): 
    
    time_start = []
    time_end = []
    
    for grouping_value in grouping_list:

        df_subset_start = df[df[grouping_col]== grouping_value]
        df_subset_end = df[df[grouping_col]== grouping_value]

        df_subset_start['trip_start_time'] = pd.to_datetime(df_subset_start['trip_start_time'])
        start_time_bins = df_subset_start.set_index('trip_start_time')
        result_start_time_bins = start_time_bins.groupby([mode_col, grouping_col]).resample('1H').size().reset_index(name='trip_count')

        df_subset_end['trip_start_time'] = pd.to_datetime(df_subset_end['trip_start_time'])
        end_time_bins = df_subset_end.set_index('trip_start_time')
        result_end_time_bins = end_time_bins.groupby([mode_col, grouping_col]).resample('1H').size().reset_index(name='trip_count')

        time_start.append(result_start_time_bins)
        time_end.append(result_end_time_bins)
            

    start_time_all = pd.concat(time_start)
    end_time_all = pd.concat(time_end)

    return start_time_all, end_time_all

In [192]:
start, end = add_hour_summary_by_mode(df_origins, "origin_city", unique_origin_list, "primary_mode")

In [193]:
alt.Chart(start).mark_bar().encode(
    x=alt.X("trip_start_time:T",axis=alt.Axis(format='%H:%M')),
    y=alt.Y("trip_count:Q", title="Number or Trips"),
    color=alt.Color("primary_mode:N", #scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)
                   ),
    # row="origin_bgrp_2020:O",
    facet=alt.Facet('origin_bgrp_2020:O').columns(4)).properties(title="Trip Start Time by Primary Mode")

alt.Chart(...)

In [194]:
alt.Chart(end).mark_bar().encode(
    x=alt.X("trip_start_time:T",axis=alt.Axis(format='%H:%M')),
    y=alt.Y("trip_count:Q", title= "Number of Trips"),
    color=alt.Color("primary_mode:N", #scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)
                   ),
    # row="origin_bgrp_2020:O",
    facet=alt.Facet('origin_bgrp_2020:O').columns(4)).properties(title="Trip End Time by Primary Mode")

alt.Chart(...)

In [195]:
# melt_dfs = []
# time_duration_dfs =  []

# for origin in unique_origin_list:
#     origins_subset = df_origins[df_origins["origin_city"] == origin]

#     origins_subset_time_melt, origins_subset_time_melt_duration = _replica_utils.return_time_metrics(origins_subset, "trip_start_time", "trip_end_time")
    
#     melt_dfs.append(origins_subset_time_melt)
#     time_duration_dfs.append(origins_subset_time_melt_duration)



# time_melt = pd.concat(melt_dfs, ignore_index=True)
# time_duration_melt = pd.concat(time_duration_dfs, ignore_index=True)

In [196]:
# alt.Chart(time_melt).mark_circle(size=150).encode(
#     x=alt.X('Time:T',axis=alt.Axis(format='%H:%M')),
#     y='Metric:O',
#     color=alt.Color("Primary Mode"),
#     tooltip = ['Primary Mode', 'Metric', 'Time'],
# ).properties(height=400, width=600, title="Trips Start and End Times")

In [197]:
# alt.Chart(time_duration_melt).mark_circle(size=150).encode(
#     x=alt.X('Value:Q', title="Minutes"),
#     y='Metric:O',
#     color=alt.Color("Primary Mode"),
#     tooltip = ['Primary Mode', 'Metric', 'Value']
# ).properties(height=400, width=600, title="Trip Duration for Trips")

In [198]:
n_trips_origin = (df_origins[df_origins['primary_mode'] != "other_travel_mode"]).groupby(["origin_city", "origin_geometry"]).agg(
        {"activity_id": "nunique"}).reset_index()
n_trips_origin = n_trips_origin.set_geometry("origin_geometry")

In [199]:
n_trips_dest = (df_dests[(df_dests['primary_mode'] != "other_travel_mode") & (df_dests['dest_city'].notna())]).groupby(["dest_city", "dest_geometry"]).agg(
        {"activity_id": "nunique"}).reset_index()
n_trips_dest = n_trips_dest.set_geometry("dest_geometry")

In [200]:
display(HTML("<h3><strong>Trips Duration</strong></h3>"))

In [229]:
# unique_origin_list

In [202]:
# agg_stats_results = []

# for city in unique_origin_list:
    
#     origins_subset = df_origins[df_origins["origin_city"] == city]
#     origins_subset = origins_subset[origins_subset["primary_mode"]!="other_travel_mode"]
    
#     k = 1.5
#     group_by_column = ["primary_mode"]
#     value_column = "trip_duration_minutes"

#     agg_stats = origins_subset.groupby(group_by_column)[value_column].describe()
    
#     agg_stats["iqr"] = agg_stats["75%"] - agg_stats["25%"]
#     agg_stats["min_"] = agg_stats["25%"] - k * agg_stats["iqr"]
#     agg_stats["max_"] = agg_stats["75%"] + k * agg_stats["iqr"]
#     data_points = origins_subset[[value_column, group_by_column]].merge(agg_stats.reset_index()[[group_by_column, "min_", "max_"]])
    
#     # This will be the lower end of the whisker
#     agg_stats["lower"] = (
#         data_points[data_points[value_column] >= data_points["min_"]]
#         .groupby(group_by_column)[value_column]
#         .min()
#     )
#     # This will be the upper end of the whisker
#     agg_stats["upper"] = (
#         data_points[data_points[value_column] <= data_points["max_"]]
#         .groupby(group_by_column)[value_column]
#         .max()
#     )
    
#     agg_stats = agg_stats.reset_index()

#     agg_stats['origin'] = city

#     agg_stats_results.append(agg_stats)

# agg_stats_all = pd.concat(agg_stats_results, ignore_index=True)

In [203]:
# agg_stats_all.sample()

In [204]:
import ipywidgets as widgets
from ipywidgets import interact

In [205]:
dropdown = widgets.Dropdown(
    options=unique_origin_list,
    value=unique_origin_list[0],
    description='Origin:',
    disabled=False,
)
output = widgets.Output()

In [206]:
# def make_chart(tract):

#     df = agg_stats_all[agg_stats_all['origin']==tract]
    
#     base = alt.Chart(df).encode(y = alt.Y("primary_mode:N", title="Primary Mode")).properties(title= f"Trip Durations for {tract}")

#     rules = base.mark_rule().encode(
#         x= alt.X("lower").title("Trip Duration (Minutes)"),
#         x2="upper",)
    
#     bars = base.mark_bar(size=14).encode(
#         x="25%",
#         x2="75%",
#         color=alt.Color("primary_mode").legend(None),)
    
#     ticks = base.mark_tick(color="white", size=14).encode(x="50%")
    
#     outliers = base.transform_flatten(flatten=["outliers"]
#                                      ).mark_point(style="boxplot-outliers").encode(
#         x="outliers:Q",
#         color="primary_mode").add_params(xcol_param).transform_filter(xcol_param)

#     chart = (rules + bars + ticks).interactive()
   
#     return chart

In [207]:
# interact(make_chart, tract=origin_tracts_list);
#

In [208]:
# ## non drop down version
# for tract in unique_origin_list:

#     agg_stats_all_subset = agg_stats_all[agg_stats_all["origin_city"] == tract ]


#     base = alt.Chart(agg_stats_all_subset).encode(y = alt.Y("primary_mode:N", title="Primary Mode")).properties(title= f"Trip Durations for {tract}")

#     rules = base.mark_rule().encode(
#         x= alt.X("lower").title("Trip Duration (Minutes)"),
#         x2="upper",)
    
#     bars = base.mark_bar(size=14).encode(
#         x="25%",
#         x2="75%",
#         color=alt.Color("primary_mode").legend(None),)
    
#     ticks = base.mark_tick(color="white", size=14).encode(
#         x="50%"
#     )
    
#     outliers = base.transform_flatten(
#         flatten=["outliers"]
#     ).mark_point(
#         style="boxplot-outliers"
#     ).encode(
#         x="outliers:Q",
#         color="primary_mode",
#     ).add_params(xcol_param).transform_filter(xcol_param)

#     chart = (rules + bars + ticks)

#     display(chart)

In [209]:
display(HTML("<h2><strong>Trips by Census Block Groups</strong></h2>"))

In [210]:
n_trips_origin = n_trips_origin.rename(columns={"activity_id":"Number of Trips", "origin_bgrp_2020":"Origin Census BlockGroup"})

n_trips_dest = n_trips_dest.rename(columns={"destination_bgrp_2020":"Destination Census BlockGroup","activity_id":"Number of Trips"})

In [211]:
display(HTML("<h4>Trips by Origin</h4>"))

In [212]:
m = n_trips_origin.explore(name="Trips from Origins", column="Number of Trips", 
                cmap="YlOrRd", tiles="CartoDB positron")
display(m)

In [213]:
# display(HTML("<h4>Trips by Destination</h3>"))

In [214]:
# n_trips_dest.sample()

In [215]:
# m = n_trips_dest.explore(name="Trips by Destination", column="Number of Trips", cmap="YlOrRd")
# m

In [216]:
# n_trips_dest_mode = (
#     origins>>filter(_.primary_mode != "other_travel_mode")).groupby(["destination_bgrp_2020", "geometry", "primary_mode"]).agg(
#         n_trips=("activity_id", "nunique"),
        
#         trip_duration_minutes_median=('trip_duration_minutes', 'median'),
#         trip_duration_minutes_mean=('trip_duration_minutes', 'mean'),
        
#         trip_distance_miles_median=('trip_distance_miles', 'median'),
#         trip_distance_miles_mean=('trip_distance_miles', 'mean'),
        
#     #     trip_start_time_mean=('trip_start_time', 'mean'),
#     #     trip_start_time_median=('trip_start_time', 'median'),
        
#     #     trip_end_time_mean=('trip_end_time', 'mean'),
#     #     trip_end_time_median=('trip_end_time', 'median'),
    
#             ).reset_index()
    
# n_trips_dest_mode = n_trips_dest_mode.set_geometry("geometry")

In [217]:
# n_trips_origin_mode = (
#     origins>>filter(_.primary_mode != "other_travel_mode")).groupby(["origin_bgrp_2020", "geometry", "primary_mode"]).agg(
#         n_trips=("activity_id", "nunique"),
        
#         trip_duration_minutes_median=('trip_duration_minutes', 'median'),
#         trip_duration_minutes_mean=('trip_duration_minutes', 'mean'),
        
#         trip_distance_miles_median=('trip_distance_miles', 'median'),
#         trip_distance_miles_mean=('trip_distance_miles', 'mean'),
        
#     #     trip_start_time_mean=('trip_start_time', 'mean'),
#     #     trip_start_time_median=('trip_start_time', 'median'),
        
#     #     trip_end_time_mean=('trip_end_time', 'mean'),
#     #     trip_end_time_median=('trip_end_time', 'median'),
    
#             ).reset_index()
        
# n_trips_origin_mode = n_trips_origin_mode.set_geometry("geometry")

In [218]:
# alt.Chart((n_trips_dest_mode>>filter(_.destination_bgrp_2020 == "1 (Tract 3570, Contra Costa, CA)"))).mark_bar().encode(
#     x=alt.X('primary_mode', title ="Trip Mode"),
#     y= alt.Y('n_trips', title="Number of Trips"),
#     # color=alt.Color('destination_bgrp_2020:N', scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS), legend=alt.Legend(title='Trip Type')),
# ).properties(width = 500, height = 400, title = "Modes by Trip Type")

In [219]:
# n_trips_from_cp_mode.sample()

In [220]:
# unique_modes = origins.primary_mode.unique()

In [221]:
# unique_modes

In [222]:
# unique_modes = ['private_auto', 'public_transit', 'walking']

In [223]:
# display(HTML("<h2>Trips Originating in the Top 20 tracts in the SCAG Area</h2>"))

In [224]:
# ##hashing out for now for saving
# replica_utils.return_mode_map(n_trips_to_cp_mode, routes, unique_modes, "to")

In [225]:
# display(HTML("<h4>Trips Destinations of the Top 20 tracts in the SCAG area</h4>"))

In [226]:
###hashing out for now for saving
# replica_utils.return_mode_map(n_trips_from_cp_mode, routes, unique_modes, "from")

In [227]:
display(HTML("<h2>Raw Trip Data Sample</h2>"))

In [228]:
df_origins.sample(3)

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,origin_geometry,origin_tract,origin_blkgrp,dest_tract,dest_blkgrp,origin_city,dest_city
56423,2831106428087994715,"1 (Tract 2674.06, Los Angeles, CA)","2674.06 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 6704.07, Los Angeles, CA)","6704.07 (Los Angeles, CA)","Los Angeles County, CA",California,public_transit,home,eat,18:57:36,21:04:28,126,28.0,unknown_vehicle_type,unknown_fuel_type,"bus, light_rail, bus, bus","Big Blue Bus, Metro - Los Angeles, Metro - Los...","Bundy Dr & Centinela Ave, Metro E Line, Metro ...",retail,retail,multi_family,multi_family,17900252617380162564,11496920837199917441,43.0,male,asian_not_hispanic_or_latino,employed,in_person,29628.0,private_auto,1,29628.0,zero,core,naics5151,multiple_units,not_attending_school,bachelors_degree,renter,asian_pacific,"1 (Tract 6704.07, Los Angeles, CA)","6704.07 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 2679.01, Los Angeles, CA)","2679.01 (Los Angeles, CA)","Los Angeles County, CA",California,8729a198effffff,8729a5674ffffff,608718334212440000,60372674061,-118.4627,34.0479,060376704071,6.087186e+17,33.7837,-118.3848,"POLYGON ((-118.45440 34.03659, -118.47055 34.0...",2674.06,1,6704.07,1,"Los Angeles, Los Angeles County","Rancho Palos Verdes, Los Angeles County"
168782,12680440647642050071,"2 (Tract 16, San Bernardino, CA)","16 (San Bernardino, CA)","San Bernardino County, CA",California,"1 (Tract 27.07, San Diego, CA)","27.07 (San Diego, CA)","San Diego County, CA",California,private_auto,work,region_arrival,11:20:00,13:02:06,102,103.2,NaN,NaN,NaN,NaN,NaN,transportation_utilities,transportation_utilities,retail,retail,4227326542249110146,14262873114344446738,28.0,female,black_not_hispanic_or_latino,employed,in_person,35614.0,private_auto,1,35614.0,one,core,not_working,multiple_units,not_attending_school,some_college,renter,english,"4 (Tract 15, San Diego, CA)","15 (San Diego, CA)","San Diego County, CA",California,"1 (Tract 27.07, San Diego, CA)","27.07 (San Diego, CA)","San Diego County, CA",California,8729a0326ffffff,8729a4181ffffff,608718237978329100,60710016002,-117.5883,34.0528,060730027071,6.087185e+17,32.7593,-117.0905,"POLYGON ((-117.58000 34.04142, -117.59622 34.0...",16,2,27.07,1,"Ontario, San Bernardino County","San Diego, San Diego County"
106221,11571130245455974529,"1 (Tract 9800.01, Los Angeles, CA)","9800.01 (Los Angeles, CA)","Los Angeles County, CA",California,"3 (Tract 423.11, Orange, CA)","423.11 (Orange, CA)","Orange County, CA",California,private_auto,home,region_arrival,18:04:00,19:41:24,97,71.4,NaN,NaN,NaN,NaN,NaN,transportation_utilities,transportation_utilities,mixed_use,single_family,16946408584481675031,1740991189412939243,62.0,male,white_not_hispanic_or_latino,employed,employed_not_working,65292.0,worked_from_home,2,201813.0,two,core,naics92,several_units,not_attending_school,high_school,renter,english,"3 (Tract 423.11, Orange, CA)","423.11 (Orange, CA)","Orange County, CA",California,"3 (Tract 423.11, Orange, CA)","423.11 (Orange, CA)","Orange County, CA",California,8729a1892ffffff,8729a54b6ffffff,608718329984581600,60379800011,-118.3445,34.2028,060590423113,6.087186e+17,33.4919,-117.6781,"POLYGON ((-118.33614 34.19148, -118.35232 34.1...",9800.01,1,423.11,3,"Burbank, Los Angeles County","San Juan Capistrano, Orange County"