In [1]:
# ! pip install calitp_data_analysis

In [2]:
%%capture

import warnings
warnings.filterwarnings('ignore')

import calitp_data_analysis.magics

In [3]:
# import shared_utils

In [4]:
import gcsfs as fs
import geopandas as gpd
import numpy as np
import pandas as pd
from calitp_data_analysis import get_fs, utils
from calitp_data_analysis.sql import to_snakecase
# from siuba import *

fs = get_fs()

In [5]:
import altair as alt
import folium
import matplotlib

In [6]:
# alt.data_transformers.enable("vegafusion")

In [7]:
# ## run this for maps to show
# ! pip install folium matplotlib mapclassify

In [8]:
#### ! pip install vegafusion
#### ! pip install "vegafusion[embed]>=1.5.0"
##### ! pip install --upgrade "vegafusion[embed]>=1.5.0" "vegafusion>=1.5.0"

In [9]:
import _replica_utils

In [10]:
from IPython.display import HTML

In [11]:
from calitp_data_analysis import calitp_color_palette as cp

In [12]:
pd.set_option("display.max_columns", None)

In [13]:
gcs_path = "gs://calitp-analytics-data/data-analyses/big_data/STM/"

In [14]:
blk_grp_url = "CA_Census_blocks_w_Cities_centered.zip"

In [15]:
display(HTML("<h1>Origin-Destination Big Data Analysis: Southern California POIs</h1>"))

In [16]:
display(HTML("This analysis uses Replica Data to identify the top trip start points within a a group of Caltrans Districts and determine what types of trips are occuring when and where."))

In [17]:
# shape_data_name = "origins/replica-stm_origin_la-03_19_26-origin_layer.zip"

# origins_name = "replica-stm_origin_la-03_18_26-trips_dataset.zip"


shape_data_name = "origins/California_hex7_layer.zip"
origins_name = "D7_8_11_12_replica-stm_regional_travel-06_25_26-trips_dataset.zip"

In [18]:
from calitp_data_analysis import utils

In [19]:
# origins = _replica_utils.read_in_and_prep_replica_data_w_shp(origins_name, shape_data_name, file_type="")

In [20]:
# origins.sample()

In [21]:
with get_fs().open(f"{gcs_path}{shape_data_name}") as f:
        shps = to_snakecase(gpd.read_file(f))

In [22]:
shps.sample()

,name,id,centrlat,centrlon,sqmi,origin,orig_sqmi,geometry
15301,87281c040ffffff,608691562372661200,41.8909,-123.8499,1.9289,20,10.3685,"POLYGON ((-123.84064 41.88105, -123.85746 41.8..."

In [23]:
len(shps)

34623

In [24]:
# shps.explore(column="geoname", tooltip=['geoname', 'customgeo', 'centrlat', 'centrlon', 'sqmi', 'origin',
#        'orig_sqmi'])

In [25]:
df = to_snakecase( pd.read_csv(f"{gcs_path}{origins_name}"))

In [26]:
df.sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng
121468,2350635615932333151,"1 (Tract 9800.28, Los Angeles, CA)","9800.28 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 427.37, Riverside, CA)","427.37 (Riverside, CA)","Riverside County, CA",California,private_auto,social,region_arrival,17:55:00,19:46:26,111,91.0,unknown_vehicle_type,electric,NaN,NaN,NaN,transportation_utilities,transportation_utilities,single_family,single_family,5422486617311102470,5405242579766252095,41.0,female,asian_not_hispanic_or_latino,employed,employed_not_working,5097.0,worked_from_home,2,213996.0,one,core,naics44_45,single_family,not_attending_school,some_college,owner,asian_pacific,"1 (Tract 432.35, Riverside, CA)","432.35 (Riverside, CA)","Riverside County, CA",California,"1 (Tract 432.35, Riverside, CA)","432.35 (Riverside, CA)","Riverside County, CA",California,8729a565bffffff,8729a0c64ffffff,608718595349807100,60379800281,-118.4119,33.9337,60650427371,6.087183e+17,33.6468,-117.0976

columns `origin_custom` & `destination_custom` are for the hex cells, geoname is lost when uploading to Replica to add to the data. check with reps.

In [27]:
df.destination_custom_id.nunique()

6703

In [28]:
df.origin_custom_id.sample()

49610    608718334212440000
Name: origin_custom_id, dtype: int64

In [29]:
df.destination_custom_id.sample()

190514    6.087186e+17
Name: destination_custom_id, dtype: float64

In [30]:
shps[shps['id']==608718594158624800]

,name,id,centrlat,centrlon,sqmi,origin,orig_sqmi,geometry
27,8729a5614ffffff,608718594158624800,33.767,-118.1908,2.232,14442,6470.5376,"POLYGON ((-118.18255 33.75568, -118.19868 33.7..."

In [31]:
# df.origin_custom_id.value_counts()

In [32]:
# df.origin_bgrp_2020.value_counts()

In [33]:
#### add in blockgroups to get the city name- another easier way to identify and group instead of a hex cell number

In [34]:
with get_fs().open(f"{gcs_path}{blk_grp_url}") as f:
        blk_grps = to_snakecase(gpd.read_file(f))

In [35]:
blk_grps = blk_grps[['objectid', 'state', 'geoid', 'tract', 'blkgrp', 'name', 'county_1', 'city', 'geometry' ]]

In [36]:
blk_grps['tract'] = blk_grps['tract'].str[:-2] + '.' + blk_grps['tract'].str[-2:]

In [37]:
df['origin_tract'] = df['origin_trct_2020'].str.split(' (', regex=False).str[0]
df['origin_blkgrp'] = df['origin_bgrp_2020'].str.split(' (', regex=False).str[0]

df['dest_tract'] = df['destination_trct_2020'].str.split(' (', regex=False).str[0]
df['dest_blkgrp'] = df['destination_bgrp_2020'].str.split(' (', regex=False).str[0]

In [38]:
df.origin_cty_2020.unique()

array(['Los Angeles County, CA', 'Orange County, CA',
       'Riverside County, CA', 'San Bernardino County, CA',
       'San Diego County, CA'], dtype=object)

In [39]:
blk_grps['county_name'] = blk_grps['county_1'] + ", CA"

In [40]:
blk_grps_subset = blk_grps[['tract', 'blkgrp', 'city', 'county_name']]

In [41]:
merged_df = pd.merge(
    df, 
    blk_grps, 
    left_on=['origin_cty_2020', 'origin_tract', 'origin_blkgrp'], 
    right_on=['county_name', 'tract', 'blkgrp'],
    how='left'
)

In [42]:
# 011100

In [43]:
condition = blk_grps['tract'].str.endswith(".00")

blk_grps['tract'] = np.where(condition, blk_grps['tract'].str.replace(".00", ""), blk_grps['tract'])

In [44]:
###### need to replace just the leading "00" and "0", not the ones that within the string (Ex: blockgroup 100 vs 0011)

In [45]:
blk_grps['corrected_tract'] = blk_grps['tract'].str.lstrip('00')
blk_grps['corrected_tract'] = blk_grps['tract'].str.lstrip('0')

In [46]:
blk_grps['city_county'] = blk_grps['city'] + ', ' + blk_grps['county_1']

In [47]:
# blk_grps[blk_grps['city']=="Unincorporated"]

In [48]:
#### check this tract that is in SD and has tract number of 0111.00
# blk_grps[blk_grps['objectid']==8376]

In [49]:
# (df[df['origin_tract'].str.startswith("83")]).origin_tract.value_counts()

In [50]:
# ((df[df['origin_trct_2020'] == "111 (San Diego, CA)"])).sample()

In [51]:
blk_grps.sample()

,objectid,state,geoid,tract,blkgrp,name,county_1,city,geometry,county_name,corrected_tract,city_county
24798,24799,06,060890124001,0124,1,Block Group 1,Shasta County,Unincorporated,"POLYGON ((-13664719.745 4966671.147, -13664728...","Shasta County, CA",124,"Unincorporated, Shasta County"

In [52]:
df.sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,origin_tract,origin_blkgrp,dest_tract,dest_blkgrp
77198,5225571628303228667,"1 (Tract 6200.01, Los Angeles, CA)","6200.01 (Los Angeles, CA)","Los Angeles County, CA",California,"2 (Tract 133.25, San Diego, CA)","133.25 (San Diego, CA)","San Diego County, CA",California,private_auto,home,shop,18:44:55,20:51:31,126,134.4,unknown_vehicle_type,other_non_bev,NaN,NaN,NaN,retail,retail,multi_family,multi_family,18232627688536019066,16583611903315948220,61.0,female,hispanic_or_latino_origin,not_in_labor_force,unemployed_under_16_not_in_labor_force,2758.0,other_travel_mode,2,2758.0,two,core,not_working,multiple_units,not_attending_school,k_12,renter,spanish,"2 (Tract 133.25, San Diego, CA)","133.25 (San Diego, CA)","San Diego County, CA",California,Does not have work/school location,Does not have work/school location,Does not have work/school location,Does not have work/school location,8729a565affffff,8729a4c53ffffff,608718595333029900,60376200011,-118.3875,33.9229,060730133252,6.087186e+17,32.6208,-116.993,6200.01,1,133.25,2

In [53]:
df2 = pd.merge(
    df, 
    blk_grps[['county_name', 'corrected_tract', 'blkgrp', 'city_county']], 
    left_on=['origin_cty_2020', 'origin_tract', 'origin_blkgrp'], 
    right_on=['county_name', 'corrected_tract', 'blkgrp'],
    how='left'
)

In [54]:
df2 = df2.drop(columns=['county_name', 'corrected_tract', 'blkgrp'])

In [55]:
df2 = df2.rename(columns={"city_county":"origin_city"})

In [56]:
df2 = pd.merge(
    df2, 
    blk_grps[['county_name', 'corrected_tract', 'blkgrp', 'city_county']], 
    left_on=['destination_cty_2020', 'dest_tract', 'dest_blkgrp'], 
    right_on=['county_name', 'corrected_tract', 'blkgrp'],
    how='left'
)

In [57]:
df2 = df2.drop(columns=['county_name', 'corrected_tract', 'blkgrp'])

In [58]:
df2 = df2.rename(columns={"city_county":"dest_city"})

In [59]:
df2

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,origin_tract,origin_blkgrp,dest_tract,dest_blkgrp,origin_city,dest_city
0,12085915017420060557,"1 (Tract 1021.04, Los Angeles, CA)","1021.04 (Los Angeles, CA)","Los Angeles County, CA",California,"2 (Tract 11, Kings, CA)","11 (Kings, CA)","Kings County, CA",California,private_auto,home,work,21:55:34,00:49:44,174,178.3,NaN,NaN,NaN,NaN,NaN,single_family,single_family,single_family,single_family,18128471139408472620,10616512179847944618,38.0,female,hispanic_or_latino_origin,not_in_labor_force,unemployed_under_16_not_in_labor_force,12108.0,other_travel_mode,7,12108.0,one,core,naics81,single_family,not_attending_school,high_school,renter,spanish,"2 (Tract 11, Kings, CA)","11 (Kings, CA)","Kings County, CA",California,Does not have work/school location,Does not have work/school location,Does not have work/school location,Does not have work/school location,8729a1892ffffff,8729a80d1ffffff,608718329984581600,60371021041,-118.3445,34.2028,060310011002,6.087188e+17,36.3205,-119.6457,1021.04,1,11,2,"Los Angeles, Los Angeles County","Hanford, Kings County"
1,12616432462675974912,"1 (Tract 1021.04, Los Angeles, CA)","1021.04 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 1114.01, Los Angeles, CA)","1114.01 (Los Angeles, CA)","Los Angeles County, CA",California,public_transit,shop,recreation,15:08:00,17:49:47,161,37.0,unknown_vehicle_type,unknown_fuel_type,bus,Metro - Los Angeles,Metro Local Line,office,office,office,office,14814586594263718632,9115706970684435042,40.0,male,hispanic_or_latino_origin,employed,in_person,4078.0,private_auto,1,4078.0,zero,core,naics56,multiple_units,not_attending_school,k_12,renter,spanish,"1 (Tract 1275.20, Los Angeles, CA)","1275.20 (Los Angeles, CA)","Los Angeles County, CA",California,"3 (Tract 3104, Los Angeles, CA)","3104 (Los Angeles, CA)","Los Angeles County, CA",California,8729a1892ffffff,8729a1125ffffff,608718329984581600,60371021041,-118.3445,34.2028,060371114011,6.087183e+17,34.2670,-118.4915,1021.04,1,1114.01,1,"Los Angeles, Los Angeles County","Los Angeles, Los Angeles County"
2,12754155054627986973,"1 (Tract 1021.04, Los Angeles, CA)","1021.04 (Los Angeles, CA)","Los Angeles County, CA",California,"3 (Tract 1212.22, Los Angeles, CA)","1212.22 (Los Angeles, CA)","Los Angeles County, CA",California,public_transit,home,work,22:32:00,00:04:19,92,11.4,unknown_vehicle_type,unknown_fuel_type,"bus, bus, bus","Metro - Los Angeles, Metro - Los Angeles, Metr...","Metro Local Line, Metro Local Line, Metro Loca...",education,education,single_family,single_family,11914740138224311444,15226853050545306300,26.0,female,white_not_hispanic_or_latino,employed,in_person,1780.0,private_auto,5,413480.0,zero,core,naics713210,single_family,not_attending_school,bachelors_degree,owner,indo_european,"3 (Tract 1212.22, Los Angeles, CA)","1212.22 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 1218.02, Los Angeles, CA)","1218.02 (Los Angeles, CA)","Los Angeles County, CA",California,8729a1892ffffff,8729a189effffff,608718329984581600,60371021041,-118.3445,34.2028,060371212223,6.087183e+17,34.2242,-118.3935,1021.04,1,1212.22,3,"Los Angeles, Los Angeles County","Los Angeles, Los Angeles County"
3,5532912666060317723,"1 (Tract 1021.04, Los Angeles, CA)","1021.04 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 1349.05, Los Angeles, CA)","1349.05 (Los Angeles, CA)","Los Angeles County, CA",California,public_transit,work,home,06:53:00,08:30:41,97,20.6,unknown_vehicle_type,unknown_fuel_type,"bus, bus","Metro - Los Angeles, Metro - Los Angeles","Metro Local Line, Metro Local Line",single_family,single_family,mixed_use,retail,7326876102754620549,9341220361429351442,51.0,female,hispanic_or_latino_origin,employed,in_person,7034.0,public_transit,4,56379.0,three_plus,core,naics61,single_family,not_attending_school,high_school,owner,english,"1 (Tract 1021.04, Los Angeles, CA)","1021.04 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 1349.05, Los Angeles, CA)","1349.05 (Los Angeles, CA)","Los Angeles County, CA",California,8729a1892ffffff,8729a18f5ffffff,608718329984581600,60371021041,-118.3445,34.2028,060371349051,6.087183e+17,34.1940,-118.5870,1021.04,1,1349.05,1,"Los Angeles, Los Angeles County","Los Angeles, Los Angeles County"
4,187967548420722133,"1 (Tract 1021.04, Los Angeles, CA)","1021.04 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 1349.05, Los Angeles, CA)","1349.05 (Los Angeles, CA)","Los Angeles County, CA",California,public_transit,work,home,08:55:00,10:51:27,116,21.6,unknown_vehicle_type,unknown_fuel_type,bus,Metro - Los Angeles,Metro Local Line,mixed_use,single_family,mixed_use,office,11748842632200535603,5731301700173594474,55.0,female,hispanic_or_latino_origin,employed,in_person,12481.0,public_transit,4,132081.0,two,core,naics621330,multiple_units,not_attending_school,k_12,renter,spanish,"1 (Tract 1021.04, Los Angeles, CA)","1021.04 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 1349.05, Los Angeles, CA)","1349.05 (Los Angeles, CA)","Los Angeles County, CA",California,8729a1892ffffff,8729a181bffffff,608718329984581600,60371021041,-118.3445,34.2028,060371349051,6.087183e+17,34.1709,-118.5865,1021.04,1,1349.05,1,"Los Angeles, Los Angeles County","Los Angeles, Los Angeles County"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201544,13172737891762857163,"2 (Tract 111, San Diego, CA)","111 (San Diego, CA)","San Diego County, CA",California,"1 (Tract 187, San Diego, CA)","187 (San Diego, CA)","San Diego County, CA",California,public_transit,home,work,10:47:13,13:47:38,180,61.5,unknown_vehicle_type,unknown_fuel_type,"bus, bus, light_rail","MTS, MTS, North County Transit District","Iris Transit Center - Downtown, Downtown - Esc...",mixed_use,retail,education,education,3332983164657358365,2050055872692723340,23.0,male,white_not_hispanic_or_latino,employed,in_person,27132.0,public_transit,1,0.0,unknown_num_vehicles,core,not_working,GQ_structure,not_attending_school,some_college,GQ,GQ_language,"1 (Tract 187, San Diego, CA)","187 (San Diego, CA)","San Diego County, CA",California,"2 (Tract 111, San Diego, CA)","111 (San Diego, CA)","San Diego County, CA",California,8729a4113ffffff,8729a4295ffffff,608718503947534300,60730111002,-117.1623,32.6991,060730187001,6.087185e+17,33.2322,-117.3605,111,2,187,1,"Coronado, San Diego County","Unincorporated, San Diego County"
201545,7926768453653944823,"2 (Tract 111, San Diego, CA)","111 (San Diego, CA)","San Diego County, CA",California,"1 (Tract 5025, Santa Clara, CA)","5025 (Santa Clara, CA)","Santa Clara County, CA",California,other_travel_mode,home,social,16:52:21,11:24:48,1112,414.8,NaN,unknown_fuel_type,NaN,NaN,NaN,single_family,single_family,single_family,single_family,13512249344798620885,3129059041892960116,54.0,female,white_not_hispanic_or_latino,not_in_labor_force,unemployed_under_16_not_in_labor_force,0.0,other_travel_mode,2,173877.0,two,core,not_working,single_family,not_attending_school,bachelors_degree,owner,english,"1 (Tract 5025, Santa Clara, CA)","5025 (Santa Clara, CA)","Santa Clara County, CA",California,Does not have work/school location,Does not have work/school location,Does not have work/school location,Does not have work/school location,8729a4113ffffff,87283444dffffff,608718503947534300,60730111002,-117.1623,32.6991,060855025001,6.086932e+17,37.3079,-121.8761,111,2,5025,1,"Coronado, San Diego County","San Jose, Santa Clara County"
201546,6824478125659441702,"2 (Tract 111, San Diego, CA)","111 (San Diego, CA)","San Diego County, CA",California,"3 (Tract 5025, Santa Clara, CA)","5025 (Santa Clara, CA)","Santa Clara County, CA",California,other_travel_mode,home,social,10:09:18,04:41:36,1112,414.7,NaN,unknown_fuel_type,NaN,NaN,NaN,single_family,single_family,single_family,single_family,12573957167786364421,6617240794821933617,46.0,female,asian_not_hispanic_or_latino,employed,remote,92734.0,worked_from_home,2,92734.0,two,core,naics54,single_family,not_attending_school,bachelors_degree,owner,indo_european,"3 (Tract 5025, Santa Clara, CA)","5025 (Santa Clara, CA)","Santa Clara County, CA",California,"3 (Tract 5025, Santa Clara, CA)","5025 (Santa Clara, CA)","Santa Clara County, CA",California,8729a4113ffffff,872834736ffffff,608718503947534300,60730111002,-117.1623,32.6991,060855025003,6.086932e+17,37.2950,-121.9000,111,2,5025,3,"Coronado, San Diego County","San Jose, Santa Clara County"
201547,11622293453042609205,"2 (Tract 111, San Diego, CA)","111 (San Diego, CA)","San Diego County, CA",California,Out of Region,Out of Region,Out of Region,Out of Region,other_travel_mode,shop,work,14:05:00,18:56:23,291,1182.4,NaN,unknown_fuel_type,NaN,NaN,NaN,mixed_use,retail,retail,retail,18195828008359383050,9073161486292758214,23.0,male,white_not_hispanic_or_latino,employed,in_person,46773.0,private_auto,1,0.0,unknown_num_vehicles,core,not_working,GQ_structure,not_attending_school,bachelors_degree,GQ,GQ_language,"1 (Tract 38, San Diego, CA)","38 (San Diego, CA)","San Diego County, CA",California,"2 (Tract 111, San Diego, CA)","111 (San Diego, CA)","San Diego County, CA",California,8729a4113ffffff,NaN,608718503947534300,60730111002,-117.1623,32.6991,Out of Region,NaN,NaN,NaN,111,2,Out of Region,Out of Region,"Coronado, San Diego County",NaN
201548,15250015820530227462,"2 (Tract 111, San Diego, CA)","111 (San Diego, CA)","San Diego County, CA",California,Out of Region,Out of Region,Out of Region,Out of Region,other_travel_mode,other_activity_type,work,13:15:00,18:06:18,291,1182.3,NaN,unknown_fuel_type,NaN,NaN,NaN,mixed_use,retail,mixed_use,industrial,6045396194582356010,1488073761285458875,25.0,male,black_not_hispanic_or_latino,employed,in_person,29678.0,walking,1,0.0,unknown_num_vehicles,core,not_working,GQ_structure,not_attending_school,high_school,GQ,GQ_language,"1 (Tract 38, San Diego, CA)","38 (San Diego, CA)","San Diego County, CA",California,"2 (Tract 111, San Diego, CA)","111 (San Diego, CA)","San Diego County, CA",California,8729a4113ffffff,NaN,608718503947534300,60730111002,-117.1623,32.6991,Out of Region,NaN,NaN,NaN,111,2,Out of Region,Out of Region,"Coronado, San Diego County",NaN

In [61]:
# df2.dest_city.value_counts()

In [58]:
df_origins, df_dests = _replica_utils.read_in_and_prep_replica_data_w_shp(origins_name, shape_data_name, 'origin_custom_id', 'destination_custom_id')

In [59]:
df_origins.sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,origin_geometry
30120,2371936002705592122,"1 (Tract 2092.01, Los Angeles, CA)","2092.01 (Los Angeles, CA)","Los Angeles County, CA",California,"3 (Tract 31.03, San Diego, CA)","31.03 (San Diego, CA)","San Diego County, CA",California,private_auto,home,recreation,20:58:00,23:07:21,129,131.5,unknown_vehicle_type,electric,NaN,NaN,NaN,office,office,single_family,single_family,11026207621124750493,1407993274264828295,77.0,male,black_not_hispanic_or_latino,not_in_labor_force,unemployed_under_16_not_in_labor_force,218854.0,other_travel_mode,2,272188.0,three_plus,core,not_working,single_family,not_attending_school,advanced_degree,owner,english,"3 (Tract 31.03, San Diego, CA)","31.03 (San Diego, CA)","San Diego County, CA",California,Does not have work/school location,Does not have work/school location,Does not have work/school location,Does not have work/school location,8729a1d62ffffff,8729a41b1ffffff,608718350654111700,60372092011,-118.2688,34.0547,060730031033,6.087185e+17,32.7135,-117.0419,"POLYGON ((-118.26050 34.04335, -118.27667 34.0..."

In [34]:
# (df_origins.sample(50)).explore(column="origin_custom_id")

In [35]:
display(HTML("<h2><strong>Trip Counts</strong></h2>"))

In [36]:
display(HTML(f"The number of trips Traveling <strong>From</strong> the top 20 locations is <strong>{len(df_origins)}</strong>"))

In [37]:
assert df_origins.origin_custom_id.nunique() == 50

In [38]:
df_origins['custom_geo_name'] = (df_origins['origin_cty_2020'].astype(str) + ' ' + df_origins['origin_custom_id'].astype(str))

In [39]:
unique_origin_list = df_origins.custom_geo_name.unique().tolist()

In [40]:
# unique_origin_list

In [41]:
summary = _replica_utils.return_score_summary_single_df(df_origins, unique_origin_list, "origin_geometry", "custom_geo_name")

In [42]:
# summary.sample()

In [43]:
summary.columns = [col.replace('_', ' ').title() for col in summary.columns]

In [44]:
# df_origins.sample()

In [45]:
summary_melt =  pd.melt(
        summary,
        id_vars=["Trip Grouping"],
        value_vars=['Trip Grouping', 'Total Trips',
                    'N Auto Trips', 'Pct Auto Trips',
                    'N Tranist Trips', 'Pct Transit Trips',
                    'N Walking Trips', 'Pct Walking Trips',
                    'Auto Mean Minutes', 'Auto Median Minutes', 'Auto Max Minutes',
                    'Auto Mean Miles','Auto Median Miles', 'Auto Max Miles',
                    'Transit Mean Minutes','Transit Median Minutes', 'Transit Max Minutes',
                    'Transit Mean Miles','Transit Median Miles', 'Transit Max Miles',
                    'Walking Mean Minutes', 'Walking Median Minutes', 'Walking Max Minutes',
                    'Walking Mean Miles','Walking Median Miles', 'Walking Max Miles',
                   ],
        var_name="Metric",  # New column for original measurement names
        # value_name="_Value"
)

In [46]:
display(HTML("<h2><strong>Trip Type Summaries</strong></h2>"))

In [47]:
list_of_dfs = []


for origin in unique_origin_list:
    origins_subset = df_origins[df_origins["custom_geo_name"] == origin]

    modes_breakdown_subset = _replica_utils.get_mode_split(origins_subset, "custom_geo_name")

    list_of_dfs.append(modes_breakdown_subset)

modes_breakdown = pd.concat(list_of_dfs, ignore_index=True)

In [48]:
modes_breakdown.columns = [col.replace('_', ' ').title() for col in modes_breakdown.columns]

In [49]:
modes_breakdown.Mode.value_counts()

Mode
other_travel_mode    50
private_auto         49
auto_passenger       48
public_transit       45
biking               44
commercial           40
on_demand_auto       33
walking              21
Name: count, dtype: int64

In [50]:
# len(modes_breakdown)

In [51]:
(modes_breakdown[modes_breakdown["Mode"]=="walking"]).sort_values('Pct Trips')

,Trip Grouping,Mode,Pct Trips,Total Trips,N Blkgrs Dest
5,"Los Angeles County, CA 608718329984581600",walking,0.000206,1,1688
118,"Los Angeles County, CA 608718334212440000",walking,0.000249,1,1512
56,"Los Angeles County, CA 608718334413766700",walking,0.000316,1,1234
274,"Riverside County, CA 608718652224569300",walking,0.000385,1,484
263,"Riverside County, CA 608718651939356700",walking,0.000543,2,601
194,"Los Angeles County, CA 608718594158624800",walking,0.000575,2,1359
185,"Los Angeles County, CA 608718596524212200",walking,0.000698,2,1367
285,"San Bernardino County, CA 608718237978329100",walking,0.000698,3,2026
258,"Riverside County, CA 608718646788751400",walking,0.001513,6,2267
322,"San Diego County, CA 608718506531225600",walking,0.001891,10,1643
164,"Los Angeles County, CA 608718334849974300",walking,0.004313,18,1736
313,"San Diego County, CA 608718503947534300",walking,0.004655,11,886
306,"San Diego County, CA 608718504064974800",walking,0.004680,57,4271
158,"Los Angeles County, CA 608718334782865400",walking,0.005426,16,1349
199,"Los Angeles County, CA 608718595333029900",walking,0.005752,15,1070
329,"San Diego County, CA 608718499820339200",walking,0.011410,25,883
298,"San Diego County, CA 608718506464116700",walking,0.035605,93,774
205,"Los Angeles County, CA 608718595349807100",walking,0.046719,850,5140
229,"Orange County, CA 608718259956482000",walking,0.285654,675,386
219,"Los Angeles County, CA 608718298946732000",walking,0.884134,4235,154
224,"Los Angeles County, CA 608718299030618100",walking,0.903700,4861,205

In [52]:
(df_origins[df_origins["origin_custom_id"]==608718595349807100]).sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,origin_geometry,custom_geo_name
129916,12933871342607225246,"1 (Tract 9800.28, Los Angeles, CA)","9800.28 (Los Angeles, CA)","Los Angeles County, CA",California,"2 (Tract 20.11, Santa Barbara, CA)","20.11 (Santa Barbara, CA)","Santa Barbara County, CA",California,private_auto,shop,region_arrival,12:19:00,15:23:25,184,176.3,unknown_vehicle_type,other_non_bev,NaN,NaN,NaN,transportation_utilities,transportation_utilities,office,office,5731566628919010897,8810190737555782153,68.0,female,white_not_hispanic_or_latino,not_in_labor_force,unemployed_under_16_not_in_labor_force,10627.0,other_travel_mode,2,115698.0,three_plus,core,not_working,single_family,not_attending_school,some_college,owner,spanish,"3 (Tract 19.08, Santa Barbara, CA)","19.08 (Santa Barbara, CA)","Santa Barbara County, CA",California,Does not have work/school location,Does not have work/school location,Does not have work/school location,Does not have work/school location,8729a565bffffff,872913691ffffff,608718595349807100,60379800281,-118.4119,33.9337,60830020112,6.087086e+17,34.9168,-120.4503,"POLYGON ((-118.40364 33.92238, -118.41978 33.9...","Los Angeles County, CA 608718595349807100"

In [130]:
alt.Chart(modes_breakdown).mark_bar().encode(
    x=alt.X("Trip Grouping:O", title = "Trip Origin"),
    y=alt.Y("Total Trips:Q", title="Total Number of Trips"),
    color=alt.Color("Mode:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    tooltip = ['Total Trips', 'Mode']
    ).properties(
    width=800,  
    height=300,
    title='Modes by Trip Type')

alt.Chart(...)

In [132]:
df_origins.sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,origin_geometry,custom_geo_name
53975,9876071152200975332,"1 (Tract 2655.21, Los Angeles, CA)","2655.21 (Los Angeles, CA)","Los Angeles County, CA",California,"2 (Tract 9006.09, Los Angeles, CA)","9006.09 (Los Angeles, CA)","Los Angeles County, CA",California,private_auto,home,work,17:53:00,19:45:24,112,73.8,NaN,NaN,NaN,NaN,NaN,office,office,single_family,single_family,13460016505357983906,10610863498543185067,50.0,female,black_not_hispanic_or_latino,employed,in_person,80916.0,private_auto,2,80916.0,two,core,naics62,single_family,not_attending_school,some_college,renter,english,"2 (Tract 9006.09, Los Angeles, CA)","9006.09 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 2655.21, Los Angeles, CA)","2655.21 (Los Angeles, CA)","Los Angeles County, CA",California,8729a199dffffff,8729a1443ffffff,608718334464098300,60372655211,-118.4387,34.0603,060379006092,6.087183e+17,34.697,-118.1099,"POLYGON ((-118.43041 34.04904, -118.44656 34.0...","Los Angeles County, CA 608718334464098300"

In [134]:
df_origins.groupby('custom_geo_name')['origin_bgrp_2020'].unique()

custom_geo_name
Los Angeles County, CA 608718298946732000       [1 (Tract 9201.02, Los Angeles, CA), 1 (Tract ...
Los Angeles County, CA 608718299030618100       [1 (Tract 9201.06, Los Angeles, CA), 1 (Tract ...
Los Angeles County, CA 608718329984581600       [1 (Tract 1021.04, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718333977559000       [1 (Tract 2713, Los Angeles, CA), 2 (Tract 271...
Los Angeles County, CA 608718333994336300       [2 (Tract 2675.02, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718334178885600       [2 (Tract 2643.05, Los Angeles, CA), 1 (Tract ...
Los Angeles County, CA 608718334212440000       [2 (Tract 2640, Los Angeles, CA), 1 (Tract 264...
Los Angeles County, CA 608718334413766700       [1 (Tract 1943, Los Angeles, CA), 2 (Tract 194...
Los Angeles County, CA 608718334447321100       [1 (Tract 2657.01, Los Angeles, CA), 1 (Tract ...
Los Angeles County, CA 608718334464098300       [1 (Tract 2651, Los Angeles, CA), 2 (Tract 265...
Los Angeles County, CA 608718334480875500       [1 (Tract 2149.02, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718334682202100       [3 (Tract 7015.01, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718334782865400       [1 (Tract 2760, Los Angeles, CA), 2 (Tract 276...
Los Angeles County, CA 608718334849974300       [1 (Tract 2772, Los Angeles, CA), 2 (Tract 277...
Los Angeles County, CA 608718345268625400       [2 (Tract 4617, Los Angeles, CA), 1 (Tract 461...
Los Angeles County, CA 608718350167572500       [1 (Tract 1905.20, Los Angeles, CA), 1 (Tract ...
Los Angeles County, CA 608718350637334500       [5 (Tract 2110, Los Angeles, CA), 2 (Tract 211...
Los Angeles County, CA 608718350654111700       [1 (Tract 2075.01, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718350670889000       [2 (Tract 1925.20, Los Angeles, CA), 1 (Tract ...
Los Angeles County, CA 608718350687666200       [1 (Tract 2218.10, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718350721220600       [1 (Tract 2077.11, Los Angeles, CA), 1 (Tract ...
Los Angeles County, CA 608718350754775000       [1 (Tract 1899.04, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718350771552300       [1 (Tract 1898.01, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718350788329500       [1 (Tract 1893, Los Angeles, CA), 2 (Tract 189...
Los Angeles County, CA 608718350838661100       [1 (Tract 1920.02, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718350888992800       [1 (Tract 1997, Los Angeles, CA), 2 (Tract 199...
Los Angeles County, CA 608718350905770000       [2 (Tract 1973, Los Angeles, CA), 3 (Tract 197...
Los Angeles County, CA 608718350972878800       [1 (Tract 2060.20, Los Angeles, CA), 1 (Tract ...
Los Angeles County, CA 608718594158624800       [2 (Tract 5758.01, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718594192179200       [2 (Tract 5733, Los Angeles, CA), 4 (Tract 573...
Los Angeles County, CA 608718595333029900       [1 (Tract 6022.01, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718595349807100       [1 (Tract 6200.01, Los Angeles, CA), 2 (Tract ...
Los Angeles County, CA 608718596524212200       [2 (Tract 5736.01, Los Angeles, CA), 3 (Tract ...
Orange County, CA 608718259956482000            [1 (Tract 320.44, Orange, CA), 2 (Tract 320.44...
Orange County, CA 608718272824606700            [1 (Tract 871.06, Orange, CA), 3 (Tract 871.06...
Orange County, CA 608718588957687800            [5 (Tract 626.10, Orange, CA), 1 (Tract 631.01...
Riverside County, CA 608718646469984300         [1 (Tract 446.02, Riverside, CA), 2 (Tract 446...
Riverside County, CA 608718646788751400         [1 (Tract 447.01, Riverside, CA), 2 (Tract 447...
Riverside County, CA 608718651939356700         [2 (Tract 451.29, Riverside, CA), 3 (Tract 451...
Riverside County, CA 608718652224569300         [1 (Tract 452.09, Riverside, CA), 1 (Tract 453...
Riverside County, CA 608718652291678200         [1 (Tract 452.07, Riverside, CA), 2 (Tract 452...
Riverside County, CA 608719708585197600                           [1 (Tract 9810, Riverside, CA)]
San Bernardino County, CA 608718237978329100    [2 (Tract 16, San Bernardino, CA), 2 (Tract 18...
San Bernardino County, CA 608718257557340200    [1 (Tract 112.03, San Bernardino, CA), 2 (Trac...
San Bernardino County, CA 608718448230400000                  [1 (Tract 250, San Bernardino, CA)]
San Diego County, CA 608718499820339200         [1 (Tract 83.05, San Diego, CA), 2 (Tract 83.0...
San Diego County, CA 608718503947534300         [1 (Tract 50, San Diego, CA), 1 (Tract 51.02, ...
San Diego County, CA 608718504064974800         [1 (Tract 2.02, San Diego, CA), 2 (Tract 2.02,...
San Diego County, CA 608718506464116700         [1 (Tract 2.01, San Diego, CA), 2 (Tract 2.01,...
San Diego County, CA 608718506531225600         [2 (Tract 51.02, San Diego, CA), 1 (Tract 52.0...
Name: origin_bgrp_2020, dtype: object

In [75]:
# (modes_breakdown[modes_breakdown['Mode']=="walking"]).sort_values('Total Trips')

In [65]:
## check the highest walking 
# (df_origins[df_origins['origin_custom_id']==608718595349807100]).explore()

In [67]:
# alt.Chart(modes_breakdown).mark_bar().encode(
#     x=alt.X('Trip Grouping:O', title ="Trip Origin"),
#     y= alt.Y('Pct Trips:Q', title="Pct of Total Trips"),
#     color=alt.Color('Trip Grouping:N', scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS), legend=alt.Legend(title='Trip Grouping')),
#     column= alt.Column('Mode:N', title="Mode"),
#     tooltip=['Pct Trips', 'Mode', 'Trip Grouping']
# ).properties(width = 100, height = 400, title = "Modes by Trip Type")

In [68]:
display(HTML("<h3><strong>Closer Look at Auto, Transit & Walking Trips</strong></h3>"))

In [69]:
display(HTML("<strong>Tip:</strong> Use the dropdown menu to select different metrics to see on the chart."))

In [70]:
metrics_list = summary_melt["Metric"].unique().tolist()

metrics_dropdown = alt.binding_select(
        options=metrics_list,
        name="Metrics: ",
    )
    # Column that controls the bar charts
xcol_param = alt.selection_point(
        fields=["Metric"], value=metrics_list[0], bind=metrics_dropdown
    )

chart = (alt.Chart(summary_melt, title="Metric by Trip Types")
        .mark_bar()
        .encode(
            x=alt.X("value"),
            y=alt.Y("Trip Grouping"),
            color=alt.Color("Trip Grouping",
                                  scale=alt.Scale(
                                      range=cp.CALITP_CATEGORY_BRIGHT_COLORS))
        ).properties(width=400, height=350)
    ).add_params(xcol_param).transform_filter(xcol_param)

display(HTML("""
<style>
form.vega-bindings {
  position: absolute;
  left: 0px;
  top: -0px;
}
</style>
"""))

(chart)

alt.Chart(...)

In [ ]:
display(HTML("<br>"
            "<br>"))

In [ ]:
summary_long_all_miles = pd.melt(
    summary,
    id_vars=["Trip Grouping"],
    value_vars=[
        'Auto Mean Miles', 'Auto Median Miles', 'Auto Max Miles', 
        'Transit Mean Miles', 'Transit Median Miles', 'Transit Max Miles',
        'Walking Mean Miles', 'Walking Median Miles', 'Walking Max Miles'],
        var_name="Metric",  # New column for original measurement names
        value_name="Miles")

In [ ]:
summary_long_all_min = pd.melt(
    summary,
    id_vars=["Trip Grouping"],
    value_vars=[
        'Auto Mean Minutes', 'Auto Median Minutes', 'Auto Max Minutes',
        'Transit Mean Minutes', 'Transit Median Minutes', 'Transit Max Minutes',
        'Walking Mean Minutes', 'Walking Median Minutes', 'Walking Max Minutes'],
        var_name="Metric",  # New column for original measurement names
        value_name="Mintues")

In [ ]:
display(HTML("<h3><strong>Trip Length</strong></h3>"))

In [ ]:
alt.Chart(summary_long_all_min).mark_bar().encode(
    x="Mintues:Q",
    y="Metric:O",
    color=alt.Color("Metric:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    # row="Trip Grouping:O",
    facet=alt.Facet('Trip Grouping:O').columns(4),
).properties(title="Travel Length by Trip Type & Mode")

In [ ]:
alt.Chart(summary_long_all_miles).mark_bar().encode(
    x="Miles:Q",
    y="Metric:O",
    color=alt.Color("Metric:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    # row="Trip Grouping:O",
    facet=alt.Facet('Trip Grouping:O').columns(4),
).properties(title="Travel Distance by Trip Type & Mode")

In [ ]:
display(HTML("<h3><strong>Trip Timing</strong></h3>"))

In [ ]:
display(HTML("<strong>Tip:</strong> You can zoom into each graph to better see the timing of the trips by mode"))

In [ ]:
import datetime

In [ ]:
def add_hour_summary_by_mode(df, grouping_col, grouping_list, mode_col): 
    
    time_start = []
    time_end = []
    
    for grouping_value in grouping_list:

        df_subset_start = df[df[grouping_col]== grouping_value]
        df_subset_end = df[df[grouping_col]== grouping_value]

        df_subset_start['trip_start_time'] = pd.to_datetime(df_subset_start['trip_start_time'])
        start_time_bins = df_subset_start.set_index('trip_start_time')
        result_start_time_bins = start_time_bins.groupby([mode_col, grouping_col]).resample('30T').size().reset_index(name='trip_count')

        df_subset_end['trip_start_time'] = pd.to_datetime(df_subset_end['trip_start_time'])
        end_time_bins = df_subset_end.set_index('trip_start_time')
        result_end_time_bins = end_time_bins.groupby([mode_col, grouping_col]).resample('30T').size().reset_index(name='trip_count')

        time_start.append(result_start_time_bins)
        time_end.append(result_end_time_bins)
            

    start_time_all = pd.concat(time_start)
    end_time_all = pd.concat(time_end)

    return start_time_all, end_time_all

In [ ]:
start, end = add_hour_summary_by_mode(origins, "origin_bgrp_2020", origin_tracts_list, "primary_mode")

In [ ]:
alt.Chart(start).mark_bar().encode(
    x=alt.X("trip_start_time:T",axis=alt.Axis(format='%H:%M')),
    y=alt.Y("trip_count:Q", title="Number or Trips"),
    color=alt.Color("primary_mode:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    # row="origin_bgrp_2020:O",
    facet=alt.Facet('origin_bgrp_2020:O').columns(4)).properties(title="Trip Start Time by Primary Mode")

In [ ]:
alt.Chart(end).mark_bar().encode(
    x=alt.X("trip_start_time:T",axis=alt.Axis(format='%H:%M')),
    y=alt.Y("trip_count:Q", title= "Number of Trips"),
    color=alt.Color("primary_mode:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    # row="origin_bgrp_2020:O",
    facet=alt.Facet('origin_bgrp_2020:O').columns(4)).properties(title="Trip End Time by Primary Mode")

In [ ]:
melt_dfs = []
time_duration_dfs =  []

for origin in origin_tracts_list:
    origins_subset = origins[origins["origin_bgrp_2020"] == origin]

    origins_subset_time_melt, origins_subset_time_melt_duration = _replica_utils.return_time_metrics(origins_subset, "trip_start_time", "trip_end_time")
    
    melt_dfs.append(origins_subset_time_melt)
    time_duration_dfs.append(origins_subset_time_melt_duration)



time_melt = pd.concat(melt_dfs, ignore_index=True)
time_duration_melt = pd.concat(time_duration_dfs, ignore_index=True)

In [ ]:
# alt.Chart(time_melt).mark_circle(size=150).encode(
#     x=alt.X('Time:T',axis=alt.Axis(format='%H:%M')),
#     y='Metric:O',
#     color=alt.Color("Primary Mode"),
#     tooltip = ['Primary Mode', 'Metric', 'Time'],
# ).properties(height=400, width=600, title="Trips Start and End Times")

In [ ]:
# alt.Chart(time_duration_melt).mark_circle(size=150).encode(
#     x=alt.X('Value:Q', title="Minutes"),
#     y='Metric:O',
#     color=alt.Color("Primary Mode"),
#     tooltip = ['Primary Mode', 'Metric', 'Value']
# ).properties(height=400, width=600, title="Trip Duration for Trips")

In [ ]:
n_trips_origin = (origins>>filter(_.primary_mode != "other_travel_mode")).groupby(["origin_bgrp_2020", "geometry"]).agg(
        {"activity_id": "nunique"}).reset_index()
n_trips_origin = n_trips_origin.set_geometry("geometry")

In [ ]:
n_trips_dest = (origins>>filter(_.primary_mode != "other_travel_mode")).groupby(["destination_bgrp_2020", "geometry"]).agg(
        {"activity_id": "nunique"}).reset_index()
n_trips_dest = n_trips_dest.set_geometry("geometry")

In [ ]:
display(HTML("<h3><strong>Trips Duration</strong></h3>"))

In [ ]:
# origin_tracts_list

In [ ]:
agg_stats_results = []

for tract in origin_tracts_list:
    
    origins_subset = origins[origins["origin_bgrp_2020"] == tract ]
    origins_subset = origins_subset[origins_subset["primary_mode"]!="other_travel_mode"]
    
    k = 1.5
    group_by_column = "primary_mode"
    value_column = "trip_duration_minutes"

    agg_stats = origins_subset.groupby(group_by_column)[value_column].describe()
    
    agg_stats["iqr"] = agg_stats["75%"] - agg_stats["25%"]
    agg_stats["min_"] = agg_stats["25%"] - k * agg_stats["iqr"]
    agg_stats["max_"] = agg_stats["75%"] + k * agg_stats["iqr"]
    data_points = origins_subset[[value_column, group_by_column]].merge(agg_stats.reset_index()[[group_by_column, "min_", "max_"]])
    
    # This will be the lower end of the whisker
    agg_stats["lower"] = (
        data_points[data_points[value_column] >= data_points["min_"]]
        .groupby(group_by_column)[value_column]
        .min()
    )
    # This will be the upper end of the whisker
    agg_stats["upper"] = (
        data_points[data_points[value_column] <= data_points["max_"]]
        .groupby(group_by_column)[value_column]
        .max()
    )
    
    agg_stats = agg_stats.reset_index()

    agg_stats['origin'] = tract

    agg_stats_results.append(agg_stats)

agg_stats_all = pd.concat(agg_stats_results, ignore_index=True)

In [ ]:
# agg_stats_all.sample()

In [ ]:
import ipywidgets as widgets
from ipywidgets import interact

In [ ]:
dropdown = widgets.Dropdown(
    options=origin_tracts_list,
    value=origin_tracts_list[0],
    description='Origin:',
    disabled=False,
)
output = widgets.Output()

In [ ]:
def make_chart(tract):

    df = agg_stats_all[agg_stats_all['origin']==tract]
    
    base = alt.Chart(df).encode(y = alt.Y("primary_mode:N", title="Primary Mode")).properties(title= f"Trip Durations for {tract}")

    rules = base.mark_rule().encode(
        x= alt.X("lower").title("Trip Duration (Minutes)"),
        x2="upper",)
    
    bars = base.mark_bar(size=14).encode(
        x="25%",
        x2="75%",
        color=alt.Color("primary_mode").legend(None),)
    
    ticks = base.mark_tick(color="white", size=14).encode(x="50%")
    
    outliers = base.transform_flatten(flatten=["outliers"]
                                     ).mark_point(style="boxplot-outliers").encode(
        x="outliers:Q",
        color="primary_mode").add_params(xcol_param).transform_filter(xcol_param)

    chart = (rules + bars + ticks).interactive()
   
    return chart

In [ ]:
interact(make_chart, tract=origin_tracts_list);

In [ ]:
### non drop down version
# for tract in origin_tracts_list:

#     agg_stats_all_subset = agg_stats_all[agg_stats_all["origin"] == tract ]


#     base = alt.Chart(agg_stats_all_subset).encode(y = alt.Y("primary_mode:N", title="Primary Mode")).properties(title= f"Trip Durations for {tract}")

#     rules = base.mark_rule().encode(
#         x= alt.X("lower").title("Trip Duration (Minutes)"),
#         x2="upper",)
    
#     bars = base.mark_bar(size=14).encode(
#         x="25%",
#         x2="75%",
#         color=alt.Color("primary_mode").legend(None),)
    
#     ticks = base.mark_tick(color="white", size=14).encode(
#         x="50%"
#     )
    
#     outliers = base.transform_flatten(
#         flatten=["outliers"]
#     ).mark_point(
#         style="boxplot-outliers"
#     ).encode(
#         x="outliers:Q",
#         color="primary_mode",
#     ).add_params(xcol_param).transform_filter(xcol_param)

#     chart = (rules + bars + ticks)

#     display(chart)

In [ ]:
display(HTML("<h2><strong>Trips by Census Block Groups</strong></h2>"))

In [ ]:
n_trips_origin = n_trips_origin.rename(columns={"activity_id":"Number of Trips", "origin_bgrp_2020":"Origin Census BlockGroup"})

n_trips_dest = n_trips_dest.rename(columns={"destination_bgrp_2020":"Destination Census BlockGroup","activity_id":"Number of Trips"})

In [ ]:
display(HTML("<h4>Trips by Origin</h4>"))

In [ ]:
m = n_trips_origin.explore(name="Trips from Origins", column="Number of Trips", 
                cmap="YlOrRd")
display(m)

In [ ]:
# display(HTML("<h4>Trips by Destination</h3>"))

In [ ]:
# n_trips_dest.sample()

In [ ]:
# m = n_trips_dest.explore(name="Trips by Destination", column="Number of Trips", cmap="YlOrRd")
# m

In [ ]:
# n_trips_dest_mode = (
#     origins>>filter(_.primary_mode != "other_travel_mode")).groupby(["destination_bgrp_2020", "geometry", "primary_mode"]).agg(
#         n_trips=("activity_id", "nunique"),
        
#         trip_duration_minutes_median=('trip_duration_minutes', 'median'),
#         trip_duration_minutes_mean=('trip_duration_minutes', 'mean'),
        
#         trip_distance_miles_median=('trip_distance_miles', 'median'),
#         trip_distance_miles_mean=('trip_distance_miles', 'mean'),
        
#     #     trip_start_time_mean=('trip_start_time', 'mean'),
#     #     trip_start_time_median=('trip_start_time', 'median'),
        
#     #     trip_end_time_mean=('trip_end_time', 'mean'),
#     #     trip_end_time_median=('trip_end_time', 'median'),
    
#             ).reset_index()
    
# n_trips_dest_mode = n_trips_dest_mode.set_geometry("geometry")

In [ ]:
# n_trips_origin_mode = (
#     origins>>filter(_.primary_mode != "other_travel_mode")).groupby(["origin_bgrp_2020", "geometry", "primary_mode"]).agg(
#         n_trips=("activity_id", "nunique"),
        
#         trip_duration_minutes_median=('trip_duration_minutes', 'median'),
#         trip_duration_minutes_mean=('trip_duration_minutes', 'mean'),
        
#         trip_distance_miles_median=('trip_distance_miles', 'median'),
#         trip_distance_miles_mean=('trip_distance_miles', 'mean'),
        
#     #     trip_start_time_mean=('trip_start_time', 'mean'),
#     #     trip_start_time_median=('trip_start_time', 'median'),
        
#     #     trip_end_time_mean=('trip_end_time', 'mean'),
#     #     trip_end_time_median=('trip_end_time', 'median'),
    
#             ).reset_index()
        
# n_trips_origin_mode = n_trips_origin_mode.set_geometry("geometry")

In [ ]:
# alt.Chart((n_trips_dest_mode>>filter(_.destination_bgrp_2020 == "1 (Tract 3570, Contra Costa, CA)"))).mark_bar().encode(
#     x=alt.X('primary_mode', title ="Trip Mode"),
#     y= alt.Y('n_trips', title="Number of Trips"),
#     # color=alt.Color('destination_bgrp_2020:N', scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS), legend=alt.Legend(title='Trip Type')),
# ).properties(width = 500, height = 400, title = "Modes by Trip Type")

In [ ]:
# n_trips_from_cp_mode.sample()

In [ ]:
# unique_modes = origins.primary_mode.unique()

In [ ]:
# unique_modes

In [ ]:
# unique_modes = ['private_auto', 'public_transit', 'walking']

In [ ]:
# display(HTML("<h2>Trips Originating in the Top 20 tracts in the SCAG Area</h2>"))

In [ ]:
# ##hashing out for now for saving
# replica_utils.return_mode_map(n_trips_to_cp_mode, routes, unique_modes, "to")

In [ ]:
# display(HTML("<h4>Trips Destinations of the Top 20 tracts in the SCAG area</h4>"))

In [ ]:
###hashing out for now for saving
# replica_utils.return_mode_map(n_trips_from_cp_mode, routes, unique_modes, "from")

In [ ]:
display(HTML("<h2>Raw Trip Data Sample</h2>"))

In [ ]:
origins.sample(3)