In [1]:
# ! pip install calitp_data_analysis

In [2]:
# ## run this for maps to show
# ! pip install folium matplotlib mapclassify

In [3]:
import shared_utils

In [4]:
%%capture

import warnings
warnings.filterwarnings('ignore')

import calitp_data_analysis.magics

In [5]:
# import shared_utils

In [6]:
import gcsfs as fs
import geopandas as gpd
import numpy as np
import pandas as pd
from calitp_data_analysis import get_fs, utils
from calitp_data_analysis.sql import to_snakecase
# from siuba import *

fs = get_fs()

In [7]:
import altair as alt
import folium
import matplotlib

In [8]:
# alt.data_transformers.enable("vegafusion")

In [9]:
#### ! pip install vegafusion
#### ! pip install "vegafusion[embed]>=1.5.0"
##### ! pip install --upgrade "vegafusion[embed]>=1.5.0" "vegafusion>=1.5.0"

In [10]:
import _replica_utils

In [11]:
from IPython.display import HTML

In [12]:
from calitp_data_analysis import calitp_color_palette as cp

In [13]:
pd.set_option("display.max_columns", None)

In [14]:
gcs_path = "gs://calitp-analytics-data/data-analyses/big_data/STM/"

In [15]:
blk_grp_url = "CA_Census_blocks_w_Cities_centered.zip"

In [16]:
display(HTML("<h1>Origin-Destination Big Data Analysis: Southern California POIs</h1>"))

In [17]:
display(HTML("This analysis uses Replica Data to identify the top trip start points within a a group of Caltrans Districts and determine what types of trips are occuring when and where."))

In [18]:
# shape_data_name = "origins/replica-stm_origin_la-03_19_26-origin_layer.zip"

# origins_name = "replica-stm_origin_la-03_18_26-trips_dataset.zip"


shape_data_name = "origins/California_hex7_layer.zip"
origins_name = "D7_8_11_12_replica-stm_regional_travel-06_25_26-trips_dataset.zip"

In [19]:
from calitp_data_analysis import utils

In [20]:
with get_fs().open(f"{gcs_path}{shape_data_name}") as f:
        shps = to_snakecase(gpd.read_file(f))

In [21]:
# len(shps)

In [22]:
# shps.sample

In [23]:
# shps.explore(column="geoname", tooltip=['geoname', 'customgeo', 'centrlat', 'centrlon', 'sqmi', 'origin',
#        'orig_sqmi'])

In [24]:
df = to_snakecase( pd.read_csv(f"{gcs_path}{origins_name}"))

In [25]:
# df.sample()

In [26]:
####### columns `origin_custom` & `destination_custom` are for the hex cells, geoname is lost when uploading to Replica to add to the data. check with reps.

In [27]:
# df.destination_custom_id.nunique()

In [28]:
# df.origin_custom_id.sample()

In [29]:
# df.destination_custom_id.sample()

In [30]:
# shps[shps['id']==608718594158624800]

In [31]:
### add in geometry column using the hex cells

In [32]:
df_origins, df_dests = _replica_utils.prep_replica_data_w_shp(df, shape_data_name, 'origin_custom_id', 'destination_custom_id')

In [33]:
# df_origins

In [34]:
# df.origin_custom_id.value_counts()

In [35]:
# df.origin_bgrp_2020.value_counts()

In [36]:
#### add in blockgroups to get the city name- another easier way to identify and group instead of a hex cell number

In [37]:
ca_place_data = "CA_Census_Block_with_Places.zip"

In [38]:
nv_place_data = "NV_Census_Block_with_Places.zip"

In [39]:
df_origins = _replica_utils.add_cities_to_origin_dest(df_origins, ca_place_data, nv_place_data, "origin_cty_2020", "origin_trct_2020", "origin_bgrp_2020", "destination_cty_2020", "destination_trct_2020", "destination_bgrp_2020")

In [40]:
df_dests = _replica_utils.add_cities_to_origin_dest(df_dests, ca_place_data, nv_place_data, "origin_cty_2020", "origin_trct_2020", "origin_bgrp_2020", "destination_cty_2020", "destination_trct_2020", "destination_bgrp_2020")

In [41]:
# df_origins.head()

In [42]:
# df_dests.head()

In [43]:
# (df_origins.sample(50)).explore(column="origin_custom_id")

In [44]:
display(HTML("<h2><strong>Trip Counts</strong></h2>"))

In [45]:
assert df_origins.origin_custom_id.nunique() == 50

In [46]:
display(HTML(f"The number of trips Traveling <strong>From</strong> the top 50 locations is <strong>{len(df_origins)}</strong>"))

In [47]:
n_hexcells = (df_origins.groupby(["origin_city"]).agg(
        {"origin_custom_id": "nunique"}).reset_index()).rename(columns={"origin_city":"Origin City", "origin_custom_id":"Number of Hex Cell Origins"})

In [48]:
alt.Chart(n_hexcells).mark_bar().encode(
    x=alt.X("Origin City:O", title = "Trip Origin City"),
    y=alt.Y("Number of Hex Cell Origins:Q", title="Total Number of Hex Cells"),
    color=alt.Color("Origin City:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    tooltip = ['Origin City', 'Number of Hex Cell Origins']
    ).properties(
    width=800,  
    height=300,
    title='Number of Origin Hex Cells by City')

alt.Chart(...)

In [49]:
n_hexcells

                              Origin City  Number of Hex Cell Origins
0                  Anaheim, Orange County                           1
1       Beverly Hills, Los Angeles County                           4
2    Big Bear City, San Bernardino County                           1
3    Big Bear Lake, San Bernardino County                           1
4                Blythe, Riverside County                           1
5             Burbank, Los Angeles County                           1
6             Castaic, Los Angeles County                           1
7              Coronado, San Diego County                           1
8               Costa Mesa, Orange County                           1
9             Coto de Caza, Orange County                           1
10        Culver City, Los Angeles County                           1
11           Del Aire, Los Angeles County                           1
12         El Segundo, Los Angeles County                           2
13            Garden Grove, Orange County                           1
14                Indio, Riverside County                           3
15          Inglewood, Los Angeles County                           1
16            La Quinta, Riverside County                           1
17     Ladera Heights, Los Angeles County                           1
18         Long Beach, Los Angeles County                           3
19        Los Angeles, Los Angeles County                          26
20           Newport Beach, Orange County                           1
21         Ontario, San Bernardino County                           1
22         Palm Springs, Riverside County                           2
23           Pasadena, Los Angeles County                           1
24  Rancho Santa Margarita, Orange County                           1
25            San Diego, San Diego County                           5
26       Santa Monica, Los Angeles County                           5
27        Signal Hill, Los Angeles County                           1
28     Unincorporated, Los Angeles County                           4
29          Unincorporated, Orange County                           1
30       Unincorporated, Riverside County                           1
31  Unincorporated, San Bernardino County                           2
32          Val Verde, Los Angeles County                           1
33     West Hollywood, Los Angeles County                           4

In [50]:
display(HTML(f"<strong>Where trips are Originating</strong>"))

In [51]:
df_origins_city = (df_origins.origin_city.value_counts().reset_index()).rename(columns={"origin_city":"Origin City", "count":"Number of Trips"})

In [52]:
alt.Chart(df_origins_city).mark_bar().encode(
    x=alt.X("Origin City:O", title = "Trip Origin City"),
    y=alt.Y("Number of Trips:Q", title="Total Number of Trips"),
    color=alt.Color("Origin City:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    tooltip = ['Origin City', 'Number of Trips']
    ).properties(
    width=800,  
    height=300,
    title='Number of Trips by City')

alt.Chart(...)

In [53]:
# df_origins_city = (df_origins.origin_custom.value_counts().reset_index()).rename(columns={"origin_city":"Origin Hex Cell", "count":"Number of Trips"})

In [54]:
# df_origins.sample()

In [55]:
df_origins_city

                              Origin City  Number of Trips
0         Los Angeles, Los Angeles County            86704
1             San Diego, San Diego County            24143
2        Santa Monica, Los Angeles County             9206
3          Long Beach, Los Angeles County             8613
4                Blythe, Riverside County             8322
5          Palm Springs, Riverside County             7050
6      Unincorporated, Los Angeles County             6601
7                 Indio, Riverside County             5388
8             Burbank, Los Angeles County             4771
9          Ontario, San Bernardino County             4296
10     West Hollywood, Los Angeles County             4282
11                 Anaheim, Orange County             4196
12           Newport Beach, Orange County             3931
13         El Segundo, Los Angeles County             3749
14            Castaic, Los Angeles County             3255
15            La Quinta, Riverside County             3051
16      Beverly Hills, Los Angeles County             2759
17           Pasadena, Los Angeles County             2412
18  Unincorporated, San Bernardino County             2329
19   Big Bear Lake, San Bernardino County             2276
20            Coto de Caza, Orange County             2245
21          Val Verde, Los Angeles County              787
22             Coronado, San Diego County              491
23           Del Aire, Los Angeles County              235
24              Costa Mesa, Orange County              142
25  Rancho Santa Margarita, Orange County              118
26          Unincorporated, Orange County               39
27            Garden Grove, Orange County               37
28        Culver City, Los Angeles County               18
29        Signal Hill, Los Angeles County               17
30     Ladera Heights, Los Angeles County               16
31          Inglewood, Los Angeles County                3
32   Big Bear City, San Bernardino County                2
33       Unincorporated, Riverside County                1

In [56]:
display(HTML(f"<strong>Where trips are Ending</strong>"))

In [57]:
df_dests['dest_city'] = df_dests['dest_city'].fillna(df_dests['dest_tract'])

In [58]:
df_dests_city = (df_dests.dest_city.value_counts().reset_index()).rename(columns={"dest_city":"Destination City", "count":"Number of Trips"})

In [59]:
df_dests[df_dests['activity_id']==12160552250801088951]

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,dest_geometry,origin_tract,origin_blkgrp,dest_tract,dest_blkgrp,origin_city,dest_city
158118,12160552250801088951,"1 (Tract 9412, Riverside, CA)","9412 (Riverside, CA)","Riverside County, CA",California,"2 (Tract 47.17, Clark, NV)","47.17 (Clark, NV)","Clark County, NV",Nevada,auto_passenger,home,region_arrival,16:35:00,21:08:11,273,267.3,unknown_vehicle_type,unknown_fuel_type,NaN,NaN,NaN,transportation_utilities,transportation_utilities,single_family,single_family,16682426200358756002,14105359217304446482,39.0,male,hispanic_or_latino_origin,employed,employed_not_working,55795.0,private_auto,4,110285.0,three_plus,core,naics23,single_family,not_attending_school,k_12,owner,spanish,"2 (Tract 47.17, Clark, NV)","47.17 (Clark, NV)","Clark County, NV",Nevada,"1 (Tract 28.42, Clark, NV)","28.42 (Clark, NV)","Clark County, NV",Nevada,8729a6255ffffff,872986169ffffff,608718646788751400,60659412001,-116.5142,33.8226,320030047172,6.087164e+17,36.1961,-115.0971,"POLYGON ((-115.08884 36.18464, -115.10554 36.1...",9412,1,47.17,2,"Palm Springs, Riverside County","Sunrise Manor, Clark County"

In [60]:
df_dests[df_dests['dest_city']=="47.17"]

Empty GeoDataFrame
Columns: [activity_id, origin_bgrp_2020, origin_trct_2020, origin_cty_2020, origin_st_2020, destination_bgrp_2020, destination_trct_2020, destination_cty_2020, destination_st_2020, primary_mode, trip_purpose, previous_trip_purpose, trip_start_time, trip_end_time, trip_duration_minutes, trip_distance_miles, vehicle_type, vehicle_fuel_type, transit_submode, transit_agency, transit_route, origin_land_use, origin_building_use, destination_land_use, destination_building_use, trip_taker_person_id, trip_taker_household_id, trip_taker_age, trip_taker_sex, trip_taker_race_ethnicity, trip_taker_employment_status, trip_taker_wfh, trip_taker_individual_income, trip_taker_commute_mode, trip_taker_household_size, trip_taker_household_income, trip_taker_available_vehicles, trip_taker_resident_type, trip_taker_industry, trip_taker_building_type, trip_taker_school_grade_attending, trip_taker_education, trip_taker_tenure, trip_taker_language, trip_taker_home_bgrp_2020, trip_taker_home_trct_2020, trip_taker_home_cty_2020, trip_taker_home_st_2020, trip_taker_work_bgrp_2020, trip_taker_work_trct_2020, trip_taker_work_cty_2020, trip_taker_work_st_2020, origin_custom, destination_custom, origin_custom_id, origin_bgrp_fips_2020, origin_custom_lng, origin_custom_lat, destination_bgrp_fips_2020, destination_custom_id, destination_custom_lat, destination_custom_lng, dest_geometry, origin_tract, origin_blkgrp, dest_tract, dest_blkgrp, origin_city, dest_city]
Index: []

In [61]:
df_dests_city

                       Destination City  Number of Trips
0                         Out of Region            26761
1       Los Angeles, Los Angeles County            12487
2           San Diego, San Diego County             7787
3           La Quinta, Riverside County             5284
4    Unincorporated, Los Angeles County             5142
..                                  ...              ...
932        Ridgemark, San Benito County                1
933        Rio Linda, Sacramento County                1
934          Loyola, Santa Clara County                1
935     French Camp, San Joaquin County                1
936          Freedom, Santa Cruz County                1

[937 rows x 2 columns]

In [118]:
(df_origins[df_origins['origin_city'].isna()]).origin_bgrp_2020.value_counts()

origin_bgrp_2020
1 (Tract 9800.33, Los Angeles, CA)    64
Name: count, dtype: int64

In [62]:
unique_origin_list = df_origins.origin_city.unique().tolist()

In [63]:
# unique_origin_list

In [64]:
df_origins.sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,origin_geometry,origin_tract,origin_blkgrp,dest_tract,dest_blkgrp,origin_city,dest_city
109048,4597096724698229890,"1 (Tract 9800.01, Los Angeles, CA)","9800.01 (Los Angeles, CA)","Los Angeles County, CA",California,Out of Region,Out of Region,Out of Region,Out of Region,other_travel_mode,social,region_arrival,08:01:00,00:37:16,996,1982.0,NaN,unknown_fuel_type,NaN,NaN,NaN,transportation_utilities,transportation_utilities,multi_family,multi_family,14071198069226373243,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,visitor,NaN,NaN,NaN,NaN,NaN,NaN,Visitor (no home location),Visitor (no home location),Visitor (no home location),Visitor (no home location),Visitor (no work/school location),Visitor (no work/school location),Visitor (no work/school location),Visitor (no work/school location),8729a1892ffffff,NaN,608718329984581600,60379800011,-118.3445,34.2028,Out of Region,NaN,NaN,NaN,"POLYGON ((-118.33614 34.19148, -118.35232 34.1...",9800.01,1,Out of Region,Out of Region,"Burbank, Los Angeles County",Out of Region

In [65]:
summary = _replica_utils.return_score_summary_single_df(df_origins, unique_origin_list, "origin_geometry", "origin_city")

Warning: No data found in the subset.

In [66]:
# summary.sample()

In [67]:
summary.columns = [col.replace('_', ' ').title() for col in summary.columns]

In [68]:
# df_origins.sample()

In [69]:
summary_melt =  pd.melt(
        summary,
        id_vars=["Trip Grouping"],
        value_vars=['Trip Grouping', 'Total Trips',
                    'N Auto Trips', 'Pct Auto Trips',
                    'N Tranist Trips', 'Pct Transit Trips',
                    'N Walking Trips', 'Pct Walking Trips',
                    'Auto Mean Minutes', 'Auto Median Minutes', 'Auto Max Minutes',
                    'Auto Mean Miles','Auto Median Miles', 'Auto Max Miles',
                    'Transit Mean Minutes','Transit Median Minutes', 'Transit Max Minutes',
                    'Transit Mean Miles','Transit Median Miles', 'Transit Max Miles',
                    'Walking Mean Minutes', 'Walking Median Minutes', 'Walking Max Minutes',
                    'Walking Mean Miles','Walking Median Miles', 'Walking Max Miles',
                   ],
        var_name="Metric",  # New column for original measurement names
        # value_name="_Value"
)

In [70]:
display(HTML("<h2><strong>Trip Type Summaries</strong></h2>"))

In [71]:
list_of_dfs = []


for origin in unique_origin_list:
    origins_subset = df_origins[df_origins["origin_city"] == origin]

    modes_breakdown_subset = _replica_utils.get_mode_split(origins_subset, "origin_city")

    list_of_dfs.append(modes_breakdown_subset)

modes_breakdown = pd.concat(list_of_dfs, ignore_index=True)

In [72]:
modes_breakdown.columns = [col.replace('_', ' ').title() for col in modes_breakdown.columns]

In [73]:
modes_breakdown.Mode.value_counts()

Mode
private_auto         33
other_travel_mode    33
auto_passenger       30
public_transit       27
biking               22
commercial           18
walking              16
on_demand_auto       12
Name: count, dtype: int64

In [74]:
# len(modes_breakdown)

In [75]:
# (modes_breakdown[modes_breakdown["Mode"]=="walking"]).sort_values('Pct Trips')

In [76]:
# (df_origins[df_origins["origin_custom_id"]==608718595349807100]).sample()

In [77]:
alt.Chart(modes_breakdown).mark_bar().encode(
    x=alt.X("Trip Grouping:O", title = "Trip Origin"),
    y=alt.Y("Total Trips:Q", title="Total Number of Trips"),
    color=alt.Color("Mode:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    tooltip = ['Total Trips', 'Mode']
    ).properties(
    width=800,  
    height=300,
    title='Modes by Trip Type')

alt.Chart(...)

In [78]:
# df_origins.sample()

In [79]:
# df_origins.groupby('origin_city')['origin_bgrp_2020'].nunique()

In [80]:
# (modes_breakdown[modes_breakdown['Mode']=="walking"]).sort_values('Total Trips')

In [81]:
## check the highest walking 
# (df_origins[df_origins['origin_custom_id']==608718595349807100]).explore()

In [82]:
# alt.Chart(modes_breakdown).mark_bar().encode(
#     x=alt.X('Trip Grouping:O', title ="Trip Origin"),
#     y= alt.Y('Pct Trips:Q', title="Pct of Total Trips"),
#     color=alt.Color('Trip Grouping:N', scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS), legend=alt.Legend(title='Trip Grouping')),
#     column= alt.Column('Mode:N', title="Mode"),
#     tooltip=['Pct Trips', 'Mode', 'Trip Grouping']
# ).properties(width = 100, height = 400, title = "Modes by Trip Type")

In [83]:
display(HTML("<h3><strong>Closer Look at Auto, Transit & Walking Trips</strong></h3>"))

In [84]:
display(HTML("<strong>Tip:</strong> Use the dropdown menu to select different metrics to see on the chart."))

In [85]:
metrics_list = summary_melt["Metric"].unique().tolist()

metrics_dropdown = alt.binding_select(
        options=metrics_list,
        name="Metrics: ",
    )
    # Column that controls the bar charts
xcol_param = alt.selection_point(
        fields=["Metric"], value=metrics_list[0], bind=metrics_dropdown
    )

chart = (alt.Chart(summary_melt, title="Metric by Trip Types")
        .mark_bar()
        .encode(
            x=alt.X("value"),
            y=alt.Y("Trip Grouping"),
            color=alt.Color("Trip Grouping",
                                  scale=alt.Scale(
                                      range=cp.CALITP_CATEGORY_BRIGHT_COLORS))
        ).properties(width=400, height=350)
    ).add_params(xcol_param).transform_filter(xcol_param)

display(HTML("""
<style>
form.vega-bindings {
  position: absolute;
  left: 0px;
  top: -0px;
}
</style>
"""))

(chart)

alt.Chart(...)

In [86]:
display(HTML("<br>"
            "<br>"))

In [87]:
summary_long_all_miles = pd.melt(
    summary,
    id_vars=["Trip Grouping"],
    value_vars=[
        'Auto Mean Miles', 'Auto Median Miles', 'Auto Max Miles', 
        'Transit Mean Miles', 'Transit Median Miles', 'Transit Max Miles',
        'Walking Mean Miles', 'Walking Median Miles', 'Walking Max Miles'],
        var_name="Metric",  # New column for original measurement names
        value_name="Miles")

In [88]:
summary_long_all_min = pd.melt(
    summary,
    id_vars=["Trip Grouping"],
    value_vars=[
        'Auto Mean Minutes', 'Auto Median Minutes', 'Auto Max Minutes',
        'Transit Mean Minutes', 'Transit Median Minutes', 'Transit Max Minutes',
        'Walking Mean Minutes', 'Walking Median Minutes', 'Walking Max Minutes'],
        var_name="Metric",  # New column for original measurement names
        value_name="Mintues")

In [89]:
display(HTML("<h3><strong>Trip Length</strong></h3>"))

In [90]:
alt.Chart(summary_long_all_min).mark_bar().encode(
    x="Mintues:Q",
    y="Metric:O",
    color=alt.Color("Metric:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    # row="Trip Grouping:O",
    facet=alt.Facet('Trip Grouping:O').columns(4),
).properties(title="Travel Length by Trip Type & Mode")

alt.Chart(...)

In [91]:
alt.Chart(summary_long_all_miles).mark_bar().encode(
    x="Miles:Q",
    y="Metric:O",
    color=alt.Color("Metric:N", scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)),
    # row="Trip Grouping:O",
    facet=alt.Facet('Trip Grouping:O').columns(4),
).properties(title="Travel Distance by Trip Type & Mode")

alt.Chart(...)

In [92]:
display(HTML("<h3><strong>Trip Timing</strong></h3>"))

In [93]:
display(HTML("<strong>Tip:</strong> You can zoom into each graph to better see the timing of the trips by mode"))

In [94]:
import datetime

In [95]:
def add_hour_summary_by_mode(df, grouping_col, grouping_list, mode_col): 
    
    time_start = []
    time_end = []
    
    for grouping_value in grouping_list:

        df_subset_start = df[df[grouping_col]== grouping_value]
        df_subset_end = df[df[grouping_col]== grouping_value]

        df_subset_start['trip_start_time'] = pd.to_datetime(df_subset_start['trip_start_time'])
        start_time_bins = df_subset_start.set_index('trip_start_time')
        result_start_time_bins = start_time_bins.groupby([mode_col, grouping_col]).resample('1h').size().reset_index(name='trip_count')

        df_subset_end['trip_start_time'] = pd.to_datetime(df_subset_end['trip_start_time'])
        end_time_bins = df_subset_end.set_index('trip_start_time')
        result_end_time_bins = end_time_bins.groupby([mode_col, grouping_col]).resample('1h').size().reset_index(name='trip_count')

        time_start.append(result_start_time_bins)
        time_end.append(result_end_time_bins)
            

    start_time_all = pd.concat(time_start)
    end_time_all = pd.concat(time_end)

    return start_time_all, end_time_all

In [96]:
start, end = add_hour_summary_by_mode(df_origins, "origin_city", unique_origin_list, "primary_mode")

In [97]:
alt.Chart(start).mark_bar().encode(
    x=alt.X("trip_start_time:T",axis=alt.Axis(format='%H:%M')),
    y=alt.Y("trip_count:Q", title="Number or Trips"),
    color=alt.Color("primary_mode:N", #scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)
                   ),
    # row="origin_bgrp_2020:O",
    facet=alt.Facet('origin_bgrp_2020:O').columns(4)).properties(title="Trip Start Time by Primary Mode")

alt.Chart(...)

In [98]:
alt.Chart(end).mark_bar().encode(
    x=alt.X("trip_start_time:T",axis=alt.Axis(format='%H:%M')),
    y=alt.Y("trip_count:Q", title= "Number of Trips"),
    color=alt.Color("primary_mode:N", #scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS)
                   ),
    # row="origin_bgrp_2020:O",
    facet=alt.Facet('origin_bgrp_2020:O').columns(4)).properties(title="Trip End Time by Primary Mode")

alt.Chart(...)

In [99]:
n_trips_origin = (df_origins[df_origins['primary_mode'] != "other_travel_mode"]).groupby(["origin_city", "origin_geometry"]).agg(
        {"activity_id": "nunique"}).reset_index()
n_trips_origin = n_trips_origin.set_geometry("origin_geometry")

In [100]:
n_trips_dest = (df_dests[(df_dests['primary_mode'] != "other_travel_mode") & (df_dests['dest_city'].notna())]).groupby(["dest_city", "dest_geometry"]).agg(
        {"activity_id": "nunique"}).reset_index()
n_trips_dest = n_trips_dest.set_geometry("dest_geometry")

In [101]:
 origins_subset = df_origins[df_origins["primary_mode"] != "other_travel_mode"]

In [102]:
melt_dfs = []
time_duration_dfs =  []

for origin in unique_origin_list:
    origins_subset = origins_subset[origins_subset["origin_city"] == origin]

    origins_subset_time_melt, origins_subset_time_melt_duration = _replica_utils.return_time_metrics(origins_subset, "trip_start_time", "trip_end_time")
    
    melt_dfs.append(origins_subset_time_melt)
    time_duration_dfs.append(origins_subset_time_melt_duration)



time_melt = pd.concat(melt_dfs, ignore_index=True)
time_duration_melt = pd.concat(time_duration_dfs, ignore_index=True)

In [103]:
alt.Chart(time_melt).mark_circle(size=150).encode(
    x=alt.X('Time:T',axis=alt.Axis(format='%H:%M')),
    y='Metric:O',
    color=alt.Color("Primary Mode"),
    tooltip = ['Primary Mode', 'Metric', 'Time'],
).properties(height=400, width=600, title="Trips Start and End Times")

alt.Chart(...)

In [104]:
alt.Chart(time_duration_melt).mark_circle(size=150).encode(
    x=alt.X('Value:Q', title="Minutes"),
    y='Metric:O',
    color=alt.Color("Primary Mode"),
    tooltip = ['Primary Mode', 'Metric', 'Value']
).properties(height=400, width=600, title="Trip Duration for Trips")

alt.Chart(...)

In [105]:
# df_origins.primary_mode.value_counts()

In [106]:
# df_origins[df_origins['primary_mode']=="other_travel_mode"]

In [107]:
display(HTML("<h3><strong>Trips Duration</strong></h3>"))

In [108]:
### currently not working --- need to further debug for vegafusion package

In [109]:
# import altair as alt
# alt.data_transformers.enable("vegafusion")

In [110]:
# df_origins.sample()

In [116]:
# unique_origin_list

In [114]:
origins_subset = df_origins[df_origins["origin_city"] == "Castaic, Los Angeles County"]

In [115]:
origins_subset

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,origin_custom_id,origin_bgrp_fips_2020,origin_custom_lng,origin_custom_lat,destination_bgrp_fips_2020,destination_custom_id,destination_custom_lat,destination_custom_lng,origin_geometry,origin_tract,origin_blkgrp,dest_tract,dest_blkgrp,origin_city,dest_city
96046,10262867254137737494,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,"2 (Tract 54.06, Fresno, CA)","54.06 (Fresno, CA)","Fresno County, CA",California,auto_passenger,maintenance,eat,19:57:00,22:56:35,179,189.1,unknown_vehicle_type,unknown_fuel_type,NaN,NaN,NaN,retail,retail,office,office,10838600259727652839,11209987165142810142,61.0,female,white_not_hispanic_or_latino,not_in_labor_force,unemployed_under_16_not_in_labor_force,0.0,other_travel_mode,2,305855.0,one,core,not_working,multiple_units,not_attending_school,bachelors_degree,renter,english,"3 (Tract 4636.02, Los Angeles, CA)","4636.02 (Los Angeles, CA)","Los Angeles County, CA",California,Does not have work/school location,Does not have work/school location,Does not have work/school location,Does not have work/school location,8729a115dffffff,8729ab98bffffff,608718299030618100,60379201181,-118.6171,34.4591,060190054062,6.087190e+17,36.8380,-119.7613,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.18,1,54.06,2,"Castaic, Los Angeles County","Fresno, Fresno County"
96047,2800331016220032294,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,"4 (Tract 61.02, Kern, CA)","61.02 (Kern, CA)","Kern County, CA",California,auto_passenger,home,social,14:53:00,16:29:12,96,85.2,unknown_vehicle_type,unknown_fuel_type,NaN,NaN,NaN,single_family,single_family,single_family,single_family,5176128346137077854,14380670415539234223,55.0,male,white_not_hispanic_or_latino,employed,in_person,450922.0,private_auto,2,571014.0,two,core,naics812910,single_family,not_attending_school,high_school,owner,indo_european,"4 (Tract 61.02, Kern, CA)","61.02 (Kern, CA)","Kern County, CA",California,"2 (Tract 9007.04, Los Angeles, CA)","9007.04 (Los Angeles, CA)","Los Angeles County, CA",California,8729a115dffffff,8729ae984ffffff,608718299030618100,60379201181,-118.6171,34.4591,060290061024,6.087192e+17,35.1230,-118.4604,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.18,1,61.02,4,"Castaic, Los Angeles County","Tehachapi, Kern County"
96048,12241904070865761279,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 1032.01, Los Angeles, CA)","1032.01 (Los Angeles, CA)","Los Angeles County, CA",California,public_transit,home,work,14:04:00,15:53:21,109,40.4,unknown_vehicle_type,unknown_fuel_type,"bus, bus, bus","Santa Clarita Transit, Santa Clarita Transit, ...","Castaic High School, ValVerde/Transit Center, ...",office,office,multi_family,multi_family,10243601142801275070,13542996871875069712,33.0,male,asian_not_hispanic_or_latino,employed,in_person,48838.0,private_auto,3,85630.0,zero,core,naics81,multiple_units,not_attending_school,bachelors_degree,renter,asian_pacific,"1 (Tract 1032.01, Los Angeles, CA)","1032.01 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,8729a115dffffff,8729a1c6affffff,608718299030618100,60379201181,-118.6171,34.4591,060371032011,6.087183e+17,34.2615,-118.3213,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.18,1,1032.01,1,"Castaic, Los Angeles County","Los Angeles, Los Angeles County"
96049,4938705193932660569,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,"3 (Tract 1330, Los Angeles, CA)","1330 (Los Angeles, CA)","Los Angeles County, CA",California,public_transit,home,work,14:42:00,17:09:34,147,38.1,unknown_vehicle_type,unknown_fuel_type,"bus, bus, bus","Santa Clarita Transit, Metro - Los Angeles, Me...","ValVerde/Transit Center, Metro G Line 901, Met...",retail,retail,mixed_use,single_family,10349064180416816595,10073382639208673838,20.0,male,hispanic_or_latino_origin,employed,in_person,25502.0,public_transit,4,164604.0,one,core,naics44_45,multiple_units,not_attending_school,some_college,renter,spanish,"3 (Tract 1330, Los Angeles, CA)","1330 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,8729a115dffffff,8729a18f4ffffff,608718299030618100,60379201181,-118.6171,34.4591,060371330003,6.087183e+17,34.1834,-118.5625,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.18,1,1330,3,"Castaic, Los Angeles County","Los Angeles, Los Angeles County"
96050,9941463292433074543,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 1914.20, Los Angeles, CA)","1914.20 (Los Angeles, CA)","Los Angeles County, CA",California,public_transit,home,work,14:49:00,16:29:38,100,36.4,unknown_vehicle_type,unknown_fuel_type,"bus, subway, bus","Santa Clarita Transit, Metro - Los Angeles, Me...","ValVerde/Transit Center, Metro B Line, Metro R...",education,education,multi_family,multi_family,6861427921592686148,8971662455799732228,43.0,female,hispanic_or_latino_origin,employed,in_person,60385.0,public_transit,3,72462.0,one,core,naics62,multiple_units,not_attending_school,some_college,renter,spanish,"1 (Tract 1914.20, Los Angeles, CA)","1914.20 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,8729a115dffffff,8729a1d45ffffff,608718299030618100,60379201181,-118.6171,34.4591,060371914201,6.087184e+17,34.0886,-118.2937,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.18,1,1914.20,1,"Castaic, Los Angeles County","Los Angeles, Los Angeles County"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99296,5476364283791964020,"3 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,Out of Region,Out of Region,Out of Region,Arizona,other_travel_mode,social,home,20:28:00,12:38:45,970,361.9,NaN,unknown_fuel_type,NaN,NaN,NaN,single_family,single_family,single_family,single_family,10713067255512331102,8681463175961703795,37.0,female,white_not_hispanic_or_latino,employed,remote,77483.0,worked_from_home,11,245703.0,three_plus,core,naics522110,single_family,not_attending_school,some_college,owner,spanish,"3 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,"3 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,8729a115dffffff,NaN,608718299030618100,60379201183,-118.6171,34.4591,Out of Region,NaN,NaN,NaN,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.18,3,Out of Region,Out of Region,"Castaic, Los Angeles County",Out of Region
99297,17714615463566578769,"3 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,Out of Region,Out of Region,Out of Region,Arizona,other_travel_mode,recreation,shop,19:11:00,11:57:27,1006,375.2,NaN,unknown_fuel_type,NaN,NaN,NaN,office,office,non_retail_attraction,non_retail_attraction,4592473133687417269,2293061054751862088,70.0,female,hispanic_or_latino_origin,not_in_labor_force,unemployed_under_16_not_in_labor_force,15670.0,other_travel_mode,5,54014.0,two,core,not_working,single_family,not_attending_school,no_school,owner,spanish,"3 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,Does not have work/school location,Does not have work/school location,Does not have work/school location,Does not have work/school location,8729a115dffffff,NaN,608718299030618100,60379201183,-118.6171,34.4591,Out of Region,NaN,NaN,NaN,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.18,3,Out of Region,Out of Region,"Castaic, Los Angeles County",Out of Region
99298,11845611871462518635,"1 (Tract 9201.19, Los Angeles, CA)","9201.19 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 9202, Los Angeles, CA)","9202 (Los Angeles, CA)","Los Angeles County, CA",California,walking,social,home,11:59:00,15:00:58,181,9.4,unknown_vehicle_type,unknown_fuel_type,NaN,NaN,NaN,single_family,single_family,civic_institutional,civic_institutional,13748259805465977363,12719797111482642468,26.0,male,hispanic_or_latino_origin,not_in_labor_force,unemployed_under_16_not_in_labor_force,13910.0,other_travel_mode,5,153012.0,zero,core,naics71,single_family,undergraduate,some_college,owner,english,"1 (Tract 9201.19, Los Angeles, CA)","9201.19 (Los Angeles, CA)","Los Angeles County, CA",California,"2 (Tract 9203.30, Los Angeles, CA)","9203.30 (Los Angeles, CA)","Los Angeles County, CA",California,8729a115dffffff,8729a1158ffffff,608718299030618100,60379201191,-118.6171,34.4591,060379202001,6.087183e+17,34.4716,-118.5930,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.19,1,9202,1,"Castaic, Los Angeles County","Unincorporated, Los Angeles County"
99299,839537343948549734,"1 (Tract 9201.19, Los Angeles, CA)","9201.19 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 9202, Los Angeles, CA)","9202 (Los Angeles, CA)","Los Angeles County, CA",California,walking,social,home,13:00:00,16:02:03,182,9.4,unknown_vehicle_type,unknown_fuel_type,NaN,NaN,NaN,single_family,single_family,civic_institutional,civic_institutional,13537980836089469545,10879597981934591215,45.0,male,white_not_hispanic_or_latino,employed,remote,202857.0,worked_from_home,4,299069.0,two,core,naics52,single_family,not_attending_school,bachelors_degree,owner,english,"1 (Tract 9201.19, Los Angeles, CA)","9201.19 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 9201.19, Los Angeles, CA)","9201.19 (Los Angeles, CA)","Los Angeles County, CA",California,8729a115dffffff,8729a1158ffffff,608718299030618100,60379201191,-118.6171,34.4591,060379202001,6.087183e+17,34.4716,-118.5930,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.19,1,9202,1,"Castaic, Los Angeles County","Unincorporated, Los Angeles County"
99300,2189946073327558,"1 (Tract 9201.19, Los Angeles, CA)","9201.19 (Los Angeles, CA)","Los Angeles County, CA",California,"3 (Tract 1527.02, Sonoma, CA)","1527.02 (Sonoma, CA)","Sonoma County, CA",California,private_auto,other_activity_type,home,22:27:00,04:45:39,378,399.2,unknown_vehicle_type,other_non_bev,NaN,NaN,NaN,single_family,single_family,office,office,3456937453153689342,13955724367864705764,33.0,male,hispanic_or_latino_origin,employed,in_person,27185.0,auto_passenger,5,60425.0,three_plus,core,naics62,single_family,not_attending_school,k_12,owner,english,"1 (Tract 9201.19, Los Angeles, CA)","9201.19 (Los Angeles, CA)","Los Angeles County, CA",California,"1 (Tract 9201.18, Los Angeles, CA)","9201.18 (Los Angeles, CA)","Los Angeles County, CA",California,8729a115dffffff,87283026effffff,608718299030618100,60379201191,-118.6171,34.4591,060971527023,6.086929e+17,38.5153,-122.7841,"POLYGON ((-118.60873 34.44786, -118.62493 34.4...",9201.19,1,1527.02,3,"Castaic, Los Angeles County","Fulton, Sonoma County"

In [112]:
agg_stats_results = []
for city in unique_origin_list:
    
    origins_subset = df_origins[df_origins["origin_city"] == city]
    # origins_subset = origins_subset[origins_subset["primary_mode"]!="other_travel_mode"]
    
    k = 1.5
    group_by_column = ["primary_mode"]
    value_column = "trip_duration_minutes"
    agg_stats = origins_subset.groupby(group_by_column).trip_duration_minutes.describe()
    
    agg_stats["iqr"] = agg_stats["75%"] - agg_stats["25%"]
    agg_stats["min_"] = agg_stats["25%"] - k * agg_stats["iqr"]
    agg_stats["max_"] = agg_stats["75%"] + k * agg_stats["iqr"]
    
    data_points = (
        origins_subset[[value_column] + group_by_column]
        .merge(
            agg_stats.reset_index()[group_by_column + ["min_", "max_"]],
            on=group_by_column)
    )
    
    agg_stats["lower"] = (
        data_points[data_points[value_column] >= data_points["min_"]]
        .groupby(group_by_column)[value_column]
        .min()
    )
    
    agg_stats["upper"] = (
        data_points[data_points[value_column] <= data_points["max_"]]
        .groupby(group_by_column)[value_column]
        .max()
    )
    
    agg_stats = agg_stats.reset_index()
    agg_stats['origin_city'] = city
    agg_stats_results.append(agg_stats)

agg_stats_all = pd.concat(agg_stats_results, ignore_index=True)

KeyError: "['primary_mode'] not in index"

In [ ]:
# agg_stats_all

In [ ]:
# len(agg_stats_all)

In [ ]:
import ipywidgets as widgets
from ipywidgets import interact

In [ ]:
dropdown = widgets.Dropdown(
    options=unique_origin_list,
    value=unique_origin_list[0],
    description='Origin:',
    disabled=False,
)
output = widgets.Output()

In [ ]:
def make_chart(tract):

    df = agg_stats_all[agg_stats_all['origin_city']==tract]
    
    base = alt.Chart(df).encode(y = alt.Y("primary_mode:N", title="Primary Mode")).properties(title= f"Trip Durations for {tract}")

    rules = base.mark_rule().encode(
        x= alt.X("lower").title("Trip Duration (Minutes)"),
        x2="upper",)
    
    bars = base.mark_bar(size=14).encode(
        x="25%",
        x2="75%",
        color=alt.Color("primary_mode").legend(None),)
    
    ticks = base.mark_tick(color="white", size=14).encode(x="50%")
    
    outliers = base.transform_flatten(flatten=["outliers"]
                                     ).mark_point(style="boxplot-outliers").encode(
        x="outliers:Q",
        color="primary_mode").add_params(xcol_param).transform_filter(xcol_param)

    chart = (rules + bars + ticks).interactive()
   
    return chart

In [ ]:
# interact(make_chart, tract=unique_origin_list);

In [ ]:
# ## non drop down version
# for tract in unique_origin_list:

#     agg_stats_all_subset = agg_stats_all[agg_stats_all["origin_city"] == tract ]


#     base = alt.Chart(agg_stats_all_subset).encode(y = alt.Y("primary_mode:N", title="Primary Mode")).properties(title= f"Trip Durations for {tract}")

#     rules = base.mark_rule().encode(
#         x= alt.X("lower").title("Trip Duration (Minutes)"),
#         x2="upper",)
    
#     bars = base.mark_bar(size=14).encode(
#         x="25%",
#         x2="75%",
#         color=alt.Color("primary_mode").legend(None),)
    
#     ticks = base.mark_tick(color="white", size=14).encode(
#         x="50%"
#     )
    
#     outliers = base.transform_flatten(
#         flatten=["outliers"]
#     ).mark_point(
#         style="boxplot-outliers"
#     ).encode(
#         x="outliers:Q",
#         color="primary_mode",
#     ).add_params(xcol_param).transform_filter(xcol_param)

#     chart = (rules + bars + ticks)

#     display(chart)

In [ ]:
display(HTML("<h2><strong>Trips by Census Block Groups</strong></h2>"))

In [ ]:
n_trips_origin = n_trips_origin.rename(columns={"activity_id":"Number of Trips", "origin_bgrp_2020":"Origin Census BlockGroup"})

n_trips_dest = n_trips_dest.rename(columns={"destination_bgrp_2020":"Destination Census BlockGroup","activity_id":"Number of Trips"})

In [ ]:
display(HTML("<h4>Trips by Origin</h4>"))

In [ ]:
m = n_trips_origin.explore(name="Trips from Origins", column="Number of Trips", 
                cmap="YlOrRd", tiles="CartoDB positron")
display(m)

In [ ]:
# display(HTML("<h4>Trips by Destination</h3>"))

In [ ]:
# n_trips_dest.sample()

In [ ]:
# m = n_trips_dest.explore(name="Trips by Destination", column="Number of Trips", cmap="YlOrRd")
# m

In [ ]:
# n_trips_dest_mode = (
#     origins>>filter(_.primary_mode != "other_travel_mode")).groupby(["destination_bgrp_2020", "geometry", "primary_mode"]).agg(
#         n_trips=("activity_id", "nunique"),
        
#         trip_duration_minutes_median=('trip_duration_minutes', 'median'),
#         trip_duration_minutes_mean=('trip_duration_minutes', 'mean'),
        
#         trip_distance_miles_median=('trip_distance_miles', 'median'),
#         trip_distance_miles_mean=('trip_distance_miles', 'mean'),
        
#     #     trip_start_time_mean=('trip_start_time', 'mean'),
#     #     trip_start_time_median=('trip_start_time', 'median'),
        
#     #     trip_end_time_mean=('trip_end_time', 'mean'),
#     #     trip_end_time_median=('trip_end_time', 'median'),
    
#             ).reset_index()
    
# n_trips_dest_mode = n_trips_dest_mode.set_geometry("geometry")

In [ ]:
# n_trips_origin_mode = (
#     origins>>filter(_.primary_mode != "other_travel_mode")).groupby(["origin_bgrp_2020", "geometry", "primary_mode"]).agg(
#         n_trips=("activity_id", "nunique"),
        
#         trip_duration_minutes_median=('trip_duration_minutes', 'median'),
#         trip_duration_minutes_mean=('trip_duration_minutes', 'mean'),
        
#         trip_distance_miles_median=('trip_distance_miles', 'median'),
#         trip_distance_miles_mean=('trip_distance_miles', 'mean'),
        
#     #     trip_start_time_mean=('trip_start_time', 'mean'),
#     #     trip_start_time_median=('trip_start_time', 'median'),
        
#     #     trip_end_time_mean=('trip_end_time', 'mean'),
#     #     trip_end_time_median=('trip_end_time', 'median'),
    
#             ).reset_index()
        
# n_trips_origin_mode = n_trips_origin_mode.set_geometry("geometry")

In [ ]:
# alt.Chart((n_trips_dest_mode>>filter(_.destination_bgrp_2020 == "1 (Tract 3570, Contra Costa, CA)"))).mark_bar().encode(
#     x=alt.X('primary_mode', title ="Trip Mode"),
#     y= alt.Y('n_trips', title="Number of Trips"),
#     # color=alt.Color('destination_bgrp_2020:N', scale=alt.Scale(range=cp.CALITP_CATEGORY_BRIGHT_COLORS), legend=alt.Legend(title='Trip Type')),
# ).properties(width = 500, height = 400, title = "Modes by Trip Type")

In [ ]:
# n_trips_from_cp_mode.sample()

In [ ]:
# unique_modes = origins.primary_mode.unique()

In [ ]:
# unique_modes

In [ ]:
# unique_modes = ['private_auto', 'public_transit', 'walking']

In [ ]:
# display(HTML("<h2>Trips Originating in the Top 20 tracts in the SCAG Area</h2>"))

In [ ]:
# ##hashing out for now for saving
# replica_utils.return_mode_map(n_trips_to_cp_mode, routes, unique_modes, "to")

In [ ]:
# display(HTML("<h4>Trips Destinations of the Top 20 tracts in the SCAG area</h4>"))

In [ ]:
###hashing out for now for saving
# replica_utils.return_mode_map(n_trips_from_cp_mode, routes, unique_modes, "from")

In [ ]:
display(HTML("<h2>Raw Trip Data Sample</h2>"))

In [ ]:
df_origins.sample(3)