In [17]:
import warnings
warnings.filterwarnings('ignore')

import calitp_data_analysis.magics

In [18]:
import gcsfs as fs
import geopandas as gpd
import numpy as np
import pandas as pd
from calitp_data_analysis import get_fs, utils
from calitp_data_analysis.sql import to_snakecase
# from siuba import *

fs = get_fs()

In [29]:
import altair as alt
import folium
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'mapclassify'

In [20]:
from IPython.display import HTML

In [21]:
pd.set_option("display.max_columns", None)

In [6]:
gcs_path = "gs://calitp-analytics-data/data-analyses/big_data/STM/"

In [7]:
shape_data_name = "replica-stm_scag_origins-origin_layer.zip"

origins_name = "replica-stm_mcog_origins_origin_layer.zip"
shape_destinations_name = "replica-stm_mcog_destinations-destination_layer.zip"

#### Check Shape Data -- Hex Cells

* When you create a study in Replica, you can download the geography breakdown that is available within the map view
* We want to change that geography breakdown to `H3 Hex Cells Resolution 7 (~2 sq mi/cell)`
* Set up your analysis as stated in the Analysis Steps
* Download the Hex Cells once you have the top 50 trip hex cells
* Upload to GCS and follow the steps below before uploading to Replica as a Custom Geographies

In [8]:
# with get_fs().open(f"{gcs_path}{shape_data_name}") as f:
#         shps = to_snakecase(gpd.read_file(f))


with get_fs().open(f"{gcs_path}origins/{origins_name}") as f:
        shps = to_snakecase(gpd.read_file(f))

In [9]:
with get_fs().open(f"{gcs_path}origins/{shape_destinations_name}") as f:
        shps = to_snakecase(gpd.read_file(f))

In [10]:
assert (len(shps) == 50)

In [11]:
shps.sample()

,geoname,customgeo,centrlat,centrlon,sqmi,destin,dest_sqmi,geometry
44,872806d4effffff,608690106613628900,39.3773,-123.337,2.0104,189,94.0099,"POLYGON ((-123.32800 39.36710, -123.34446 39.3..."

In [12]:
shps = shps.set_geometry("geometry")

In [13]:
# (shps.sample()).explore()

* Rename the columns to match Replica's Custom Geographies specs

In [14]:
shps = shps.rename(columns={"geoname":"name", "customgeo":"id"})

In [15]:
shps.sample()

,name,id,centrlat,centrlon,sqmi,destin,dest_sqmi,geometry
14,872806d2cffffff,608690106043203600,39.2454,-123.2037,2.0166,768,380.8321,"POLYGON ((-123.19473 39.23511, -123.21118 39.2..."

In [16]:
geojson_string = shps.to_json()

* Run the cell below `geojson_string`
* Copy and paste the string in a new file
* Rename the file "Shps_{County}_Origins.geojson"
* Download the new geojson and upload to Replica Custom Geographies
* Use the newly uploaded Geography as the custom geography for the Trip Data Download (steps detailed in Analysis Steps)

In [17]:
geojson_string

'{"type": "FeatureCollection", "features": [{"id": "0", "type": "Feature", "properties": {"name": "8728316abffffff", "id": 608693033046638600, "centrlat": 39.1355, "centrlon": -123.1962, "sqmi": 2.0197, "destin": 5419, "dest_sqmi": 2683.106}, "geometry": {"type": "Polygon", "coordinates": [[[-123.187240573, 39.125197849], [-123.203678209, 39.123788041], [-123.212646512, 39.134077515], [-123.205177356, 39.145777898], [-123.188736333, 39.147188861], [-123.179767853, 39.136898286], [-123.187240573, 39.125197849]]]}}, {"id": "1", "type": "Feature", "properties": {"name": "87283168dffffff", "id": 608693032543322100, "centrlat": 39.1575, "centrlon": -123.1977, "sqmi": 2.0191, "destin": 3562, "dest_sqmi": 1764.1803}, "geometry": {"type": "Polygon", "coordinates": [[[-123.188736333, 39.147188861], [-123.205177356, 39.145777898], [-123.21414767, 39.156064585], [-123.206677139, 39.167763335], [-123.190232729, 39.169175453], [-123.181262237, 39.158887665], [-123.188736333, 39.147188861]]]}}, {"id": "2", "type": "Feature", "properties": {"name": "8728316f2ffffff", "id": 608693034237820900, "centrlat": 39.1663, "centrlon": -123.2231, "sqmi": 2.0183, "destin": 1932, "dest_sqmi": 957.2336}, "geometry": {"type": "Polygon", "coordinates": [[[-123.21414767, 39.156064585], [-123.23058696, 39.154649789], [-123.239559105, 39.164932588], [-123.232092142, 39.176631282], [-123.215649466, 39.178047234], [-123.206677139, 39.167763335], [-123.21414767, 39.156064585]]]}}, {"id": "3", "type": "Feature", "properties": {"name": "872806858ffffff", "id": 608690085306564600, "centrlat": 39.4339, "centrlon": -123.8125, "sqmi": 1.9991, "destin": 1737, "dest_sqmi": 868.908}, "geometry": {"type": "Polygon", "coordinates": [[[-123.803494761, 39.423733624], [-123.81990249, 39.422227275], [-123.828921849, 39.432411796], [-123.821533756, 39.444103755], [-123.805122663, 39.445611294], [-123.796103028, 39.435425683], [-123.803494761, 39.423733624]]]}}, {"id": "4", "type": "Feature", "properties": {"name": "8728316d6ffffff", "id": 608693033768058900, "centrlat": 39.2014, "centrlon": -123.2007, "sqmi": 2.0179, "destin": 1638, "dest_sqmi": 811.7536}, "geometry": {"type": "Polygon", "coordinates": [[[-123.19172976, 39.19115762], [-123.20817756, 39.189744349], [-123.217151899, 39.200025456], [-123.209678618, 39.211720932], [-123.193227428, 39.213135357], [-123.18425291, 39.202853151], [-123.19172976, 39.19115762]]]}}, {"id": "5", "type": "Feature", "properties": {"name": "872806d4affffff", "id": 608690106546520000, "centrlat": 39.3993, "centrlon": -123.3385, "sqmi": 2.0098, "destin": 1607, "dest_sqmi": 799.5763}, "geometry": {"type": "Polygon", "coordinates": [[[-123.329527738, 39.389031813], [-123.34599052, 39.387591255], [-123.354988121, 39.397833229], [-123.347523143, 39.409516855], [-123.331056967, 39.41095857], [-123.322059165, 39.400715503], [-123.329527738, 39.389031813]]]}}, {"id": "6", "type": "Feature", "properties": {"name": "872806d4bffffff", "id": 608690106563297300, "centrlat": 39.4081, "centrlon": -123.364, "sqmi": 2.0091, "destin": 1435, "dest_sqmi": 714.2646}, "geometry": {"type": "Polygon", "coordinates": [[[-123.354988121, 39.397833229], [-123.371449127, 39.396388827], [-123.380448546, 39.406626892], [-123.372987166, 39.418310451], [-123.356522767, 39.419756012], [-123.347523143, 39.409516855], [-123.354988121, 39.397833229]]]}}, {"id": "7", "type": "Feature", "properties": {"name": "8728316f6ffffff", "id": 608693034304929800, "centrlat": 39.1444, "centrlon": -123.2216, "sqmi": 2.0189, "destin": 1263, "dest_sqmi": 625.5813}, "geometry": {"type": "Polygon", "coordinates": [[[-123.212646512, 39.134077515], [-123.229082417, 39.132663876], [-123.23805255, 39.142949463], [-123.23058696, 39.154649789], [-123.21414767, 39.156064585], [-123.205177356, 39.145777898], [-123.212646512, 39.134077515]]]}}, {"id": "8", "type": "Feature", "properties": {"name": "87280685affffff", "id": 608690085340119000, "centrlat": 39.4471, "centrlon": -123.7887, "sqmi": 1.9992, "destin": 1260, "dest_sqmi": 630.2479}, "geometry": {"type": "Polygon", "coordinates": [[[-123.779690049, 39.436929398], [-123.796103028, 39.435425683], [-123.805122663, 39.445611294], [-123.797729593, 39.457301708], [-123.781313248, 39.458806609], [-123.772293339, 39.44861991], [-123.779690049, 39.436929398]]]}}, {"id": "9", "type": "Feature", "properties": {"name": "87280685bffffff", "id": 608690085356896300, "centrlat": 39.4558, "centrlon": -123.8141, "sqmi": 1.9985, "destin": 968, "dest_sqmi": 484.3754}, "geometry": {"type": "Polygon", "coordinates": [[[-123.805122663, 39.445611294], [-123.821533756, 39.444103755], [-123.830555143, 39.454285442], [-123.823165715, 39.465975756], [-123.806751257, 39.467484483], [-123.797729593, 39.457301708], [-123.805122663, 39.445611294]]]}}, {"id": "10", "type": "Feature", "properties": {"name": "872806549ffffff", "id": 608690072170004500, "centrlat": 39.7932, "centrlon": -123.2414, "sqmi": 2.0012, "destin": 912, "dest_sqmi": 455.7242}, "geometry": {"type": "Polygon", "coordinates": [[[-123.232391413, 39.782984743], [-123.24893124, 39.781540543], [-123.257960274, 39.791745429], [-123.250449666, 39.803395598], [-123.233906411, 39.804840935], [-123.224877191, 39.794634967], [-123.232391413, 39.782984743]]]}}, {"id": "11", "type": "Feature", "properties": {"name": "87280695bffffff", "id": 608690089651863600, "centrlat": 39.3026, "centrlon": -123.8027, "sqmi": 2.0027, "destin": 884, "dest_sqmi": 441.4012}, "geometry": {"type": "Polygon", "coordinates": [[[-123.793741835, 39.292373799], [-123.810129409, 39.290874598], [-123.819136619, 39.301076078], [-123.81175653, 39.312777851], [-123.7953656, 39.314278245], [-123.786358116, 39.304075672], [-123.793741835, 39.292373799]]]}}, {"id": "12", "type": "Feature", "properties": {"name": "872806031ffffff", "id": 608690050292514800, "centrlat": 39.6839, "centrlon": -123.483, "sqmi": 1.9993, "destin": 874, "dest_sqmi": 437.1639}, "geometry": {"type": "Polygon", "coordinates": [[[-123.47398588, 39.67368907], [-123.490477069, 39.672216522], [-123.499506061, 39.682407732], [-123.49204409, 39.694072573], [-123.475549497, 39.695546278], [-123.466520281, 39.685353984], [-123.47398588, 39.67368907]]]}}, {"id": "13", "type": "Feature", "properties": {"name": "8728316a8ffffff", "id": 608693032996307000, "centrlat": 39.1135, "centrlon": -123.1947, "sqmi": 2.0203, "destin": 851, "dest_sqmi": 421.2288}, "geometry": {"type": "Polygon", "coordinates": [[[-123.185745447, 39.103202423], [-123.202179699, 39.10179377], [-123.211145991, 39.112086028], [-123.203678209, 39.123788041], [-123.187240573, 39.125197849], [-123.178274104, 39.114904489], [-123.185745447, 39.103202423]]]}}, {"id": "14", "type": "Feature", "properties": {"name": "872806d2cffffff", "id": 608690106043203600, "centrlat": 39.2454, "centrlon": -123.2037, "sqmi": 2.0166, "destin": 768, "dest_sqmi": 380.8321}, "geometry": {"type": "Polygon", "coordinates": [[[-123.194725732, 39.235108658], [-123.211180314, 39.233693081], [-123.220158683, 39.243968599], [-123.212682648, 39.255660791], [-123.196224673, 39.257077519], [-123.187246126, 39.246800904], [-123.194725732, 39.235108658]]]}}, {"id": "15", "type": "Feature", "properties": {"name": "8728316d4ffffff", "id": 608693033734504400, "centrlat": 39.1883, "centrlon": -123.2246, "sqmi": 2.0177, "destin": 740, "dest_sqmi": 366.7526}, "geometry": {"type": "Polygon", "coordinates": [[[-123.215649466, 39.178047234], [-123.232092142, 39.176631282], [-123.2410663, 39.18691129], [-123.233597964, 39.198608349], [-123.217151899, 39.200025456], [-123.20817756, 39.189744349], [-123.215649466, 39.178047234]]]}}, {"id": "16", "type": "Feature", "properties": {"name": "872831689ffffff", "id": 608693032476213200, "centrlat": 39.1795, "centrlon": -123.1992, "sqmi": 2.0185, "destin": 677, "dest_sqmi": 335.404}, "geometry": {"type": "Polygon", "coordinates": [[[-123.190232729, 39.169175453], [-123.206677139, 39.167763335], [-123.215649466, 39.178047234], [-123.20817756, 39.189744349], [-123.19172976, 39.19115762], [-123.182757256, 39.180872622], [-123.190232729, 39.169175453]]]}}, {"id": "17", "type": "Feature", "properties": {"name": "87280685cffffff", "id": 608690085373673500, "centrlat": 39.412, "centrlon": -123.8109, "sqmi": 1.9997, "destin": 575, "dest_sqmi": 287.5473}, "geometry": {"type": "Polygon", "coordinates": [[[-123.801867549, 39.401851479], [-123.818271916, 39.400346319], [-123.827289248, 39.410533673], [-123.81990249, 39.422227275], [-123.803494761, 39.423733624], [-123.794477153, 39.413545181], [-123.801867549, 39.401851479]]]}}, {"id": "18", "type": "Feature", "properties": {"name": "8728316a9ffffff", "id": 608693033013084200, "centrlat": 39.1224, "centrlon": -123.2201, "sqmi": 2.0195, "destin": 542, "dest_sqmi": 268.3795}, "geometry": {"type": "Polygon", "coordinates": [[[-123.211145991, 39.112086028], [-123.227578512, 39.110673546], [-123.236546634, 39.120961919], [-123.229082417, 39.132663876], [-123.212646512, 39.134077515], [-123.203678209, 39.123788041], [-123.211145991, 39.112086028]]]}}, {"id": "19", "type": "Feature", "properties": {"name": "872831780ffffff", "id": 608693036620185600, "centrlat": 38.9767, "centrlon": -123.1111, "sqmi": 2.0255, "destin": 498, "dest_sqmi": 245.8594}, "geometry": {"type": "Polygon", "coordinates": [[[-123.102159241, 38.966403232], [-123.118581725, 38.965011834], [-123.127532476, 38.975329603], [-123.120060907, 38.987039876], [-123.103635041, 38.988432427], [-123.094684127, 38.978113553], [-123.102159241, 38.966403232]]]}}, {"id": "20", "type": "Feature", "properties": {"name": "872806910ffffff", "id": 608690088393572400, "centrlat": 39.1801, "centrlon": -123.571, "sqmi": 2.0108, "destin": 489, "dest_sqmi": 243.1904}, "geometry": {"type": "Polygon", "coordinates": [[[-123.562035467, 39.169811539], [-123.578432983, 39.168349044], [-123.5874203, 39.178591299], [-123.58001034, 39.190297148], [-123.563609461, 39.191760823], [-123.554621906, 39.18151747], [-123.562035467, 39.169811539]]]}}, {"id": "21", "type": "Feature", "properties": {"name": "872806bb0ffffff", "id": 608690099667861500, "centrlat": 39.4909, "centrlon": -123.792, "sqmi": 1.998, "destin": 453, "dest_sqmi": 226.7279}, "geometry": {"type": "Polygon", "coordinates": [[[-123.782937136, 39.480679337], [-123.799356849, 39.479173248], [-123.808380542, 39.489353187], [-123.800984796, 39.501040301], [-123.784561714, 39.502547575], [-123.775537747, 39.492366549], [-123.782937136, 39.480679337]]]}}, {"id": "22", "type": "Feature", "properties": {"name": "872806d2dffffff", "id": 608690106059980800, "centrlat": 39.2542, "centrlon": -123.2291, "sqmi": 2.0159, "destin": 444, "dest_sqmi": 220.2507}, "geometry": {"type": "Polygon", "coordinates": [[[-123.220158683, 39.243968599], [-123.236611527, 39.242549183], [-123.245591729, 39.252820806], [-123.23811927, 39.264512941], [-123.221663033, 39.26593351], [-123.212682648, 39.255660791], [-123.220158683, 39.243968599]]]}}, {"id": "23", "type": "Feature", "properties": {"name": "872806c64ffffff", "id": 608690102687760400, "centrlat": 39.4212, "centrlon": -123.3401, "sqmi": 2.0092, "destin": 405, "dest_sqmi": 201.5726}, "geometry": {"type": "Polygon", "coordinates": [[[-123.331056967, 39.41095857], [-123.347523143, 39.409516855], [-123.356522767, 39.419756012], [-123.349056418, 39.431437976], [-123.332586846, 39.432880847], [-123.323587021, 39.422640598], [-123.331056967, 39.41095857]]]}}, {"id": "24", "type": "Feature", "properties": {"name": "872831389ffffff", "id": 608693019591311400, "centrlat": 38.9032, "centrlon": -123.6993, "sqmi": 2.0152, "destin": 392, "dest_sqmi": 194.5199}, "geometry": {"type": "Polygon", "coordinates": [[[-123.690331003, 38.892965535], [-123.706667289, 38.891498069], [-123.715635022, 38.901758806], [-123.708266726, 38.913488116], [-123.691927104, 38.914956781], [-123.682959115, 38.904694937], [-123.690331003, 38.892965535]]]}}, {"id": "25", "type": "Feature", "properties": {"name": "87280685effffff", "id": 608690085407227900, "centrlat": 39.4252, "centrlon": -123.7871, "sqmi": 1.9998, "destin": 370, "dest_sqmi": 185.0163}, "geometry": {"type": "Polygon", "coordinates": [[[-123.778067539, 39.415047707], [-123.794477153, 39.413545181], [-123.803494761, 39.423733624], [-123.796103028, 39.435425683], [-123.779690049, 39.436929398], [-123.770672168, 39.426739865], [-123.778067539, 39.415047707]]]}}, {"id": "26", "type": "Feature", "properties": {"name": "8728316aaffffff", "id": 608693033029861400, "centrlat": 39.1266, "centrlon": -123.1708, "sqmi": 2.0204, "destin": 350, "dest_sqmi": 173.2308}, "geometry": {"type": "Polygon", "coordinates": [[[-123.161834742, 39.116310466], [-123.178274104, 39.114904489], [-123.187240573, 39.125197849], [-123.179767853, 39.136898286], [-123.163325104, 39.138305416], [-123.154358462, 39.128010955], [-123.161834742, 39.116310466]]]}}, {"id": "27", "type": "Feature", "properties": {"name": "872806d28ffffff", "id": 608690105976094700, "centrlat": 39.2674, "centrlon": -123.2052, "sqmi": 2.016, "destin": 346, "dest_sqmi": 171.6247}, "geometry": {"type": "Polygon", "coordinates": [[[-123.196224673, 39.257077519], [-123.212682648, 39.255660791], [-123.221663033, 39.26593351], [-123.214185621, 39.277624055], [-123.197724251, 39.279041935], [-123.188743688, 39.268768119], [-123.196224673, 39.257077519]]]}}, {"id": "28", "type": "Feature", "properties": {"name": "872806094ffffff", "id": 608690051953459200, "centrlat": 39.8019, "centrlon": -123.267, "sqmi": 2.0005, "destin": 338, "dest_sqmi": 168.9615}, "geometry": {"type": "Polygon", "coordinates": [[[-123.257960274, 39.791745429], [-123.274498336, 39.790297351], [-123.283529216, 39.800498303], [-123.276022227, 39.812148413], [-123.259480738, 39.81359763], [-123.250449666, 39.803395598], [-123.257960274, 39.791745429]]]}}, {"id": "29", "type": "Feature", "properties": {"name": "872806d29ffffff", "id": 608690105992872000, "centrlat": 39.2762, "centrlon": -123.2306, "sqmi": 2.0153, "destin": 320, "dest_sqmi": 158.7873}, "geometry": {"type": "Polygon", "coordinates": [[[-123.221663033, 39.26593351], [-123.23811927, 39.264512941], [-123.247101488, 39.274781763], [-123.239627653, 39.286472251], [-123.223168023, 39.287893973], [-123.214185621, 39.277624055], [-123.221663033, 39.26593351]]]}}, {"id": "30", "type": "Feature", "properties": {"name": "8728316d2ffffff", "id": 608693033700950000, "centrlat": 39.2234, "centrlon": -123.2022, "sqmi": 2.0172, "destin": 316, "dest_sqmi": 156.6492}, "geometry": {"type": "Polygon", "coordinates": [[[-123.193227428, 39.213135357], [-123.209678618, 39.211720932], [-123.218654972, 39.221999246], [-123.211180314, 39.233693081], [-123.194725732, 39.235108658], [-123.1857492, 39.224829247], [-123.193227428, 39.213135357]]]}}, {"id": "31", "type": "Feature", "properties": {"name": "872806892ffffff", "id": 608690086279643100, "centrlat": 39.4388, "centrlon": -123.391, "sqmi": 2.0077, "destin": 284, "dest_sqmi": 141.4561}, "geometry": {"type": "Polygon", "coordinates": [[[-123.38198861, 39.428545697], [-123.398451225, 39.427096291], [-123.407454484, 39.437327625], [-123.399995337, 39.449009454], [-123.383529328, 39.450460018], [-123.37452586, 39.440227594], [-123.38198861, 39.428545697]]]}}, {"id": "32", "type": "Feature", "properties": {"name": "872806bb4ffffff", "id": 608690099734970400, "centrlat": 39.469, "centrlon": -123.7903, "sqmi": 1.9986, "destin": 276, "dest_sqmi": 138.0965}, "geometry": {"type": "Polygon", "coordinates": [[[-123.781313248, 39.458806609], [-123.797729593, 39.457301708], [-123.806751257, 39.467484483], [-123.799356849, 39.479173248], [-123.782937136, 39.480679337], [-123.773915199, 39.470495473], [-123.781313248, 39.458806609]]]}}, {"id": "33", "type": "Feature", "properties": {"name": "87283162cffffff", "id": 608693030915932200, "centrlat": 38.9996, "centrlon": -123.3603, "sqmi": 2.0198, "destin": 269, "dest_sqmi": 133.1793}, "geometry": {"type": "Polygon", "coordinates": [[[-123.351311304, 38.989324643], [-123.367706336, 38.987898547], [-123.376669279, 38.998185864], [-123.369237393, 39.009900382], [-123.352838995, 39.01132765], [-123.343875849, 39.001039228], [-123.351311304, 38.989324643]]]}}, {"id": "34", "type": "Feature", "properties": {"name": "872806d48ffffff", "id": 608690106512965600, "centrlat": 39.3861, "centrlon": -123.3625, "sqmi": 2.0097, "destin": 259, "dest_sqmi": 128.8768}, "geometry": {"type": "Polygon", "coordinates": [[[-123.353454127, 39.375905971], [-123.369911741, 39.374462727], [-123.378909138, 39.384703609], [-123.371449127, 39.396388827], [-123.354988121, 39.397833229], [-123.34599052, 39.387591255], [-123.353454127, 39.375905971]]]}}, {"id": "35", "type": "Feature", "properties": {"name": "8728310edffffff", "id": 608693008384131100, "centrlat": 38.7622, "centrlon": -123.5412, "sqmi": 2.0221, "destin": 254, "dest_sqmi": 125.6094}, "geometry": {"type": "Polygon", "coordinates": [[[-123.53225585, 38.751941342], [-123.54858971, 38.750501386], [-123.55753889, 38.760796439], [-123.55015444, 38.77253256], [-123.533817241, 38.773973708], [-123.524867832, 38.763677544], [-123.53225585, 38.751941342]]]}}, {"id": "36", "type": "Feature", "properties": {"name": "8728063a0ffffff", "id": 608690065039687700, "centrlat": 39.8711, "centrlon": -123.7208, "sqmi": 1.9893, "destin": 240, "dest_sqmi": 120.6457}, "geometry": {"type": "Polygon", "coordinates": [[[-123.711735758, 39.86093605], [-123.7282273, 39.859422962], [-123.737282634, 39.86956439], [-123.729846691, 39.881219983], [-123.713351748, 39.88273424], [-123.70429615, 39.872591735], [-123.711735758, 39.86093605]]]}}, {"id": "37", "type": "Feature", "properties": {"name": "87283128cffffff", "id": 608693015346675700, "centrlat": 39.0263, "centrlon": -123.6836, "sqmi": 2.0124, "destin": 238, "dest_sqmi": 118.2672}, "geometry": {"type": "Polygon", "coordinates": [[[-123.674581534, 39.016070467], [-123.690939705, 39.014599618], [-123.699917734, 39.024847549], [-123.692537848, 39.036567432], [-123.676176332, 39.038039474], [-123.667198049, 39.02779044], [-123.674581534, 39.016070467]]]}}, {"id": "38", "type": "Feature", "properties": {"name": "87283168cffffff", "id": 608693032526544900, "centrlat": 39.1486, "centrlon": -123.1723, "sqmi": 2.0198, "destin": 236, "dest_sqmi": 116.8421}, "geometry": {"type": "Polygon", "coordinates": [[[-123.163325104, 39.138305416], [-123.179767853, 39.136898286], [-123.188736333, 39.147188861], [-123.181262237, 39.158887665], [-123.164816099, 39.160295948], [-123.155847446, 39.150004273], [-123.163325104, 39.138305416]]]}}, {"id": "39", "type": "Feature", "properties": {"name": "872806096ffffff", "id": 608690051987013600, "centrlat": 39.815, "centrlon": -123.2429, "sqmi": 2.0006, "destin": 219, "dest_sqmi": 109.468}, "geometry": {"type": "Polygon", "coordinates": [[[-123.233906411, 39.804840935], [-123.250449666, 39.803395598], [-123.259480738, 39.81359763], [-123.251968741, 39.825246081], [-123.235422056, 39.826692555], [-123.226390798, 39.816489442], [-123.233906411, 39.804840935]]]}}, {"id": "40", "type": "Feature", "properties": {"name": "872806022ffffff", "id": 608690050040856600, "centrlat": 39.6707, "centrlon": -123.507, "sqmi": 1.9991, "destin": 203, "dest_sqmi": 101.5451}, "geometry": {"type": "Polygon", "coordinates": [[[-123.497937673, 39.660549992], [-123.514423639, 39.659074748], [-123.523452402, 39.669264874], [-123.515995428, 39.680931328], [-123.499506061, 39.682407732], [-123.490477069, 39.672216522], [-123.497937673, 39.660549992]]]}}, {"id": "41", "type": "Feature", "properties": {"name": "872806d1cffffff", "id": 608690105774768100, "centrlat": 39.3197, "centrlon": -123.1094, "sqmi": 2.0166, "destin": 203, "dest_sqmi": 100.665}, "geometry": {"type": "Polygon", "coordinates": [[[-123.100387869, 39.309470277], [-123.116866339, 39.308064339], [-123.125847416, 39.318341443], [-123.118350189, 39.330025581], [-123.101868314, 39.331432661], [-123.092887073, 39.321154462], [-123.100387869, 39.309470277]]]}}, {"id": "42", "type": "Feature", "properties": {"na

In [18]:
# saved = to_snakecase(gpd.read_file("./saved-selection-geo-stm-scag-top50-origins_h3z7.geojson"))

In [19]:
# saved

##### Checking to see if geonames match

In [20]:
shps[shps['id']==608718595349807100]

Empty GeoDataFrame
Columns: [name, id, centrlat, centrlon, sqmi, destin, dest_sqmi, geometry]
Index: []

#### Check Trips Data

In [34]:
trips = "replica-stm_mtc_origins-06_11_26-trips_dataset.zip"

In [35]:
df = to_snakecase(pd.read_csv(f"{gcs_path}{trips}"))

In [36]:
df.sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,tour_type,trip_start_local_hour,trip_end_local_hour,origin_custom_id,destination_custom_id,origin_zcta_2020,destination_zcta_2020,destination_custom_lat,destination_custom_lng,origin_custom_lng,origin_custom_lat
494816,11450995759283825128,"1 (Tract 9821, Alameda, CA)","9821 (Alameda, CA)","Alameda County, CA",California,"2 (Tract 611.01, San Francisco, CA)","611.01 (San Francisco, CA)","San Francisco County, CA",California,biking,recreation,recreation,04:30:00,05:59:15,89,15.1,unknown_vehicle_type,unknown_fuel_type,NaN,NaN,NaN,non_retail_attraction,non_retail_attraction,retail,retail,17490821120225364441,17872052184154803393,68.0,male,black_not_hispanic_or_latino,not_in_labor_force,unemployed_under_16_not_in_labor_force,5911.0,other_travel_mode,1,5911.0,zero,core,not_working,single_family,not_attending_school,some_college,owner,english,"4 (Tract 4219, Alameda, CA)","4219 (Alameda, CA)","Alameda County, CA",California,Does not have work/school location,Does not have work/school location,Does not have work/school location,Does not have work/school location,8728308a8ffffff,87283082affffff,other_home_based,4,5,608692972866764800,6.086930e+17,94720,94111,37.7865,-122.3945,-122.2513,37.8646

In [37]:
len(df.origin_custom_id.value_counts())

50

In [38]:
# df.columns

In [39]:
df.destination_custom_id.nunique()

8254

In [40]:
len(df[df['destination_custom_id']==None])

0

In [42]:
# df.destination_custom_id.info()

In [27]:
with get_fs().open(f"{gcs_path}origins/replica-stm_hex_cells-origin_layer.zip") as f:
        hex_cells = to_snakecase(gpd.read_file(f))

In [28]:
hex_cells.sample()

,geoname,customgeo,centrlat,centrlon,sqmi,origin,orig_sqmi,geometry
20265,872989358ffffff,608716658269225000,39.7014,-120.3176,2.0577,8,3.8879,"POLYGON ((-120.30870 39.69083, -120.32555 39.6..."

In [29]:
hex_cells = hex_cells.set_geometry("geometry")

In [30]:
hex_cells = hex_cells.rename(columns={"geoname":"name", "customgeo":"id"})

In [31]:
hex_geojson_string = hex_cells.to_json()

In [32]:
# hex_geojson_string

In [33]:
# with open("hex7_layer.geojson", "w") as file:
#     file.write(hex_geojson_string)

In [33]:
utils.make_zipped_shapefile(hex_cells, "hex7_layer.zip")

Path name: hex7_layer.zip
Dirname (1st element of path): hex7_layer
Shapefile name: hex7_layer.shp
Shapefile component parts folder: hex7_layer/hex7_layer.shp

In [22]:
hexcells = to_snakecase(gpd.read_file("hex7_layer.zip"))

In [23]:
hexcells.sample()

,name,id,centrlat,centrlon,sqmi,origin,orig_sqmi,geometry
26770,87283370effffff,608693172146536400,39.5543,-122.1255,2.0296,3,1.4781,"POLYGON ((-122.11653 39.54390, -122.13316 39.5..."

In [24]:
len(hexcells)

34623

In [30]:
hexcells = hexcells.set_geometry("geometry")

In [39]:
# (hexcells.sample(50)).explore()

In [33]:
# ! pip install folium matplotlib mapclassify