In [1]:
import warnings
warnings.filterwarnings('ignore')

import calitp_data_analysis.magics

In [2]:
import gcsfs as fs
import geopandas as gpd
import numpy as np
import pandas as pd
from calitp_data_analysis import get_fs, utils
from calitp_data_analysis.sql import to_snakecase
# from siuba import *

fs = get_fs()

In [3]:
import altair as alt
import folium
import matplotlib.pyplot as plt

In [4]:
from IPython.display import HTML

In [5]:
pd.set_option("display.max_columns", None)

In [6]:
gcs_path = "gs://calitp-analytics-data/data-analyses/big_data/STM/"

In [63]:
shape_data_name = "replica-stm_scag_origins-origin_layer.zip"

origins_name = "replica-mtc_scag_origins-origin_layer.zip"
shape_destinations_name = "replica-mtc_scag_destinations-destination_layer.zip"

#### Check Shape Data -- Hex Cells

* When you create a study in Replica, you can download the geography breakdown that is available within the map view
* We want to change that geography breakdown to `H3 Hex Cells Resolution 7 (~2 sq mi/cell)`
* Set up your analysis as stated in the Analysis Steps
* Download the Hex Cells once you have the top 50 trip hex cells
* Upload to GCS and follow the steps below before uploading to Replica as a Custom Geographies

In [73]:
# with get_fs().open(f"{gcs_path}{shape_data_name}") as f:
#         shps = to_snakecase(gpd.read_file(f))

# with get_fs().open(f"{gcs_path}origins/{shape_destinations_name}") as f:
#         shps = to_snakecase(gpd.read_file(f))

with get_fs().open(f"{gcs_path}origins/{origins_name}") as f:
        shps = to_snakecase(gpd.read_file(f))

In [74]:
assert (len(shps) == 50)

In [75]:
shps.sample()

,geoname,customgeo,centrlat,centrlon,sqmi,origin,orig_sqmi,geometry
22,872830812ffffff,608692970350182400,37.82,-122.2488,2.072,7695,3713.7247,"POLYGON ((-122.23995 37.80942, -122.25629 37.8..."

In [76]:
shps = shps.set_geometry("geometry")

In [77]:
# (shps.sample()).explore()

* Rename the columns to match Replica's Custom Geographies specs

In [78]:
shps = shps.rename(columns={"geoname":"name", "customgeo":"id"})

In [79]:
shps.sample()

,name,id,centrlat,centrlon,sqmi,origin,orig_sqmi,geometry
39,87283098bffffff,608692976675192800,37.7883,-122.2223,2.0733,5437,2622.339,"POLYGON ((-122.21352 37.77777, -122.22986 37.7..."

In [80]:
geojson_string = shps.to_json()

* Run the cell below `geojson_string`
* Copy and paste the string in a new file
* Rename the file "Shps_{County}_Origins.geojson"
* Download the new geojson and upload to Replica Custom Geographies
* Use the newly uploaded Geography as the custom geography for the Trip Data Download (steps detailed in Analysis Steps)

In [81]:
geojson_string

'{"type": "FeatureCollection", "features": [{"id": "0", "type": "Feature", "properties": {"name": "87283082affffff", "id": 608692970752835600, "centrlat": 37.7865, "centrlon": -122.3945, "sqmi": 2.0699, "origin": 54041, "orig_sqmi": 26107.4026}, "geometry": {"type": "Polygon", "coordinates": [[[-122.385634554, 37.776004201], [-122.401953852, 37.774760714], [-122.410770923, 37.785293474], [-122.403268745, 37.797070861], [-122.386946098, 37.798315483], [-122.378128979, 37.787781581], [-122.385634554, 37.776004201]]]}}, {"id": "1", "type": "Feature", "properties": {"name": "872830828ffffff", "id": 608692970719281200, "centrlat": 37.7735, "centrlon": -122.4183, "sqmi": 2.0698, "origin": 30692, "orig_sqmi": 14828.5789}, "geometry": {"type": "Polygon", "coordinates": [[[-122.409454632, 37.762981848], [-122.425769087, 37.761735734], [-122.434586108, 37.77226735], [-122.427088725, 37.784046223], [-122.410770923, 37.785293474], [-122.401953852, 37.774760714], [-122.409454632, 37.762981848]]]}}, {"id": "2", "type": "Feature", "properties": {"name": "87283082bffffff", "id": 608692970769612800, "centrlat": 37.7958, "centrlon": -122.4196, "sqmi": 2.0692, "origin": 30356, "orig_sqmi": 14670.2675}, "geometry": {"type": "Polygon", "coordinates": [[[-122.410770923, 37.785293474], [-122.427088725, 37.784046223], [-122.435907697, 37.794575223], [-122.428408918, 37.806352616], [-122.412087767, 37.807601004], [-122.403268745, 37.797070861], [-122.410770923, 37.785293474]]]}}, {"id": "3", "type": "Feature", "properties": {"name": "872830905ffffff", "id": 608692974427045900, "centrlat": 37.6209, "centrlon": -122.3602, "sqmi": 2.0746, "origin": 28783, "orig_sqmi": 13873.7633}, "geometry": {"type": "Polygon", "coordinates": [[[-122.351370275, 37.610387961], [-122.367667646, 37.609156188], [-122.376469182, 37.619710934], [-122.368973389, 37.6314986], [-122.352672677, 37.63273151], [-122.3438711, 37.622175616], [-122.351370275, 37.610387961]]]}}, {"id": "4", "type": "Feature", "properties": {"name": "872830829ffffff", "id": 608692970736058400, "centrlat": 37.7828, "centrlon": -122.4434, "sqmi": 2.0691, "origin": 18092, "orig_sqmi": 8744.0819}, "geometry": {"type": "Polygon", "coordinates": [[[-122.434586108, 37.77226735], [-122.450899062, 37.771017473], [-122.459717979, 37.781545331], [-122.452223997, 37.793324207], [-122.435907697, 37.794575223], [-122.427088725, 37.784046223], [-122.434586108, 37.77226735]]]}}, {"id": "5", "type": "Feature", "properties": {"name": "872830810ffffff", "id": 608692970316628000, "centrlat": 37.807, "centrlon": -122.2726, "sqmi": 2.0719, "origin": 17685, "orig_sqmi": 8535.7004}, "geometry": {"type": "Polygon", "coordinates": [[[-122.263815848, 37.796422715], [-122.280152595, 37.795194678], [-122.288965962, 37.805738379], [-122.281442611, 37.817511256], [-122.265102507, 37.818740418], [-122.256289112, 37.808195576], [-122.263815848, 37.796422715]]]}}, {"id": "6", "type": "Feature", "properties": {"name": "872834711ffffff", "id": 608693240916344800, "centrlat": 37.3717, "centrlon": -121.9287, "sqmi": 2.0892, "origin": 16020, "orig_sqmi": 7668.1538}, "geometry": {"type": "Polygon", "coordinates": [[[-121.919917088, 37.361085704], [-121.93622528, 37.359922214], [-121.944986294, 37.370550583], [-121.937439091, 37.382343597], [-121.921127548, 37.383508197], [-121.91236656, 37.372878673], [-121.919917088, 37.361085704]]]}}, {"id": "7", "type": "Feature", "properties": {"name": "87283082effffff", "id": 608692970819944400, "centrlat": 37.7642, "centrlon": -122.3931, "sqmi": 2.0705, "origin": 13897, "orig_sqmi": 6711.8506}, "geometry": {"type": "Polygon", "coordinates": [[[-122.384323562, 37.753688825], [-122.400639512, 37.752446475], [-122.409454632, 37.762981848], [-122.401953852, 37.774760714], [-122.385634554, 37.776004201], [-122.376819386, 37.765467684], [-122.384323562, 37.753688825]]]}}, {"id": "8", "type": "Feature", "properties": {"name": "87283082cffffff", "id": 608692970786390000, "centrlat": 37.7512, "centrlon": -122.417, "sqmi": 2.0704, "origin": 13385, "orig_sqmi": 6465.0778}, "geometry": {"type": "Polygon", "coordinates": [[[-122.408138896, 37.740666132], [-122.424450005, 37.739421156], [-122.433265075, 37.749955385], [-122.425769087, 37.761735734], [-122.409454632, 37.762981848], [-122.400639512, 37.752446475], [-122.408138896, 37.740666132]]]}}, {"id": "9", "type": "Feature", "properties": {"name": "87283082dffffff", "id": 608692970803167200, "centrlat": 37.7605, "centrlon": -122.4421, "sqmi": 2.0696, "origin": 11549, "orig_sqmi": 5580.2413}, "geometry": {"type": "Polygon", "coordinates": [[[-122.433265075, 37.749955385], [-122.449574684, 37.748706648], [-122.45839165, 37.75923712], [-122.450899062, 37.771017473], [-122.434586108, 37.77226735], [-122.425769087, 37.761735734], [-122.433265075, 37.749955385]]]}}, {"id": "10", "type": "Feature", "properties": {"name": "8728308a8ffffff", "id": 608692972866764800, "centrlat": 37.8646, "centrlon": -122.2513, "sqmi": 2.0709, "origin": 10915, "orig_sqmi": 5270.6491}, "geometry": {"type": "Polygon", "coordinates": [[[-122.242511863, 37.854051527], [-122.258860152, 37.852823893], [-122.26767745, 37.863363502], [-122.260146485, 37.875131883], [-122.243794833, 37.876360638], [-122.23497751, 37.86581989], [-122.242511863, 37.854051527]]]}}, {"id": "11", "type": "Feature", "properties": {"name": "8728308a9ffffff", "id": 608692972883542000, "centrlat": 37.8739, "centrlon": -122.2765, "sqmi": 2.0702, "origin": 9875, "orig_sqmi": 4770.1285}, "geometry": {"type": "Polygon", "coordinates": [[[-122.26767745, 37.863363502], [-122.284024275, 37.862132091], [-122.292843497, 37.872667939], [-122.285315923, 37.884436337], [-122.268965735, 37.885668871], [-122.260146485, 37.875131883], [-122.26767745, 37.863363502]]]}}, {"id": "12", "type": "Feature", "properties": {"name": "872834449ffffff", "id": 608693228970967000, "centrlat": 37.3303, "centrlon": -121.8773, "sqmi": 2.0911, "origin": 9712, "orig_sqmi": 4644.3361}, "geometry": {"type": "Polygon", "coordinates": [[[-121.868581065, 37.319699778], [-121.884888629, 37.318544897], [-121.8936438, 37.329183224], [-121.886091373, 37.340977587], [-121.869780458, 37.342133576], [-121.861025321, 37.331494093], [-121.868581065, 37.319699778]]]}}, {"id": "13", "type": "Feature", "properties": {"name": "87283092effffff", "id": 608692975114911700, "centrlat": 37.6079, "centrlon": -122.384, "sqmi": 2.0745, "origin": 9492, "orig_sqmi": 4575.6277}, "geometry": {"type": "Polygon", "coordinates": [[[-122.375162043, 37.597367065], [-122.391454593, 37.596132678], [-122.400256083, 37.606686275], [-122.39276507, 37.618475408], [-122.376469182, 37.619710934], [-122.367667646, 37.609156188], [-122.375162043, 37.597367065]]]}}, {"id": "14", "type": "Feature", "properties": {"name": "87283474effffff", "id": 608693241939755000, "centrlat": 37.4436, "centrlon": -122.1781, "sqmi": 2.0825, "origin": 9071, "orig_sqmi": 4355.791}, "geometry": {"type": "Polygon", "coordinates": [[[-122.169371423, 37.43300899], [-122.185662276, 37.431809133], [-122.194440734, 37.442402917], [-122.186928353, 37.454197713], [-122.17063416, 37.455398698], [-122.161855689, 37.44480376], [-122.169371423, 37.43300899]]]}}, {"id": "15", "type": "Feature", "properties": {"name": "87283095affffff", "id": 608692975853109200, "centrlat": 37.7698, "centrlon": -122.4672, "sqmi": 2.0689, "origin": 8959, "orig_sqmi": 4330.3353}, "geometry": {"type": "Polygon", "coordinates": [[[-122.45839165, 37.75923712], [-122.474699753, 37.757984622], [-122.483518612, 37.768511336], [-122.476029426, 37.780291691], [-122.459717979, 37.781545331], [-122.450899062, 37.771017473], [-122.45839165, 37.75923712]]]}}, {"id": "16", "type": "Feature", "properties": {"name": "872830950ffffff", "id": 608692975685337100, "centrlat": 37.7159, "centrlon": -122.4394, "sqmi": 2.0708, "origin": 8889, "orig_sqmi": 4292.6352}, "geometry": {"type": "Polygon", "coordinates": [[[-122.430624675, 37.705319203], [-122.446927599, 37.704072747], [-122.455740665, 37.714608441], [-122.448250863, 37.726391737], [-122.431944597, 37.727639334], [-122.423131477, 37.717102495], [-122.430624675, 37.705319203]]]}}, {"id": "17", "type": "Feature", "properties": {"name": "872830951ffffff", "id": 608692975702114300, "centrlat": 37.7251, "centrlon": -122.4646, "sqmi": 2.07, "origin": 8827, "orig_sqmi": 4264.1988}, "geometry": {"type": "Polygon", "coordinates": [[[-122.455740665, 37.714608441], [-122.472042085, 37.713358227], [-122.480857042, 37.723890167], [-122.47337064, 37.735673466], [-122.457065879, 37.736924822], [-122.448250863, 37.726391737], [-122.455740665, 37.714608441]]]}}, {"id": "18", "type": "Feature", "properties": {"name": "872834714ffffff", "id": 608693240966676500, "centrlat": 37.3398, "centrlon": -121.9024, "sqmi": 2.0904, "origin": 8763, "orig_sqmi": 4191.9545}, "geometry": {"type": "Polygon", "coordinates": [[[-121.8936438, 37.329183224], [-121.909950006, 37.328024593], [-121.918707136, 37.338659218], [-121.911158029, 37.350453628], [-121.894848472, 37.351613367], [-121.886091373, 37.340977587], [-121.8936438, 37.329183224]]]}}, {"id": "19", "type": "Feature", "properties": {"name": "8728309aaffffff", "id": 608692977195286500, "centrlat": 37.7213, "centrlon": -122.2185, "sqmi": 2.075, "origin": 8407, "orig_sqmi": 4051.481}, "geometry": {"type": "Polygon", "coordinates": [[[-122.209692125, 37.71076874], [-122.226021713, 37.709551616], [-122.234825388, 37.720110641], [-122.227299496, 37.731887935], [-122.210966553, 37.733106183], [-122.202162858, 37.722546013], [-122.209692125, 37.71076874]]]}}, {"id": "20", "type": "Feature", "properties": {"name": "872830958ffffff", "id": 608692975819554800, "centrlat": 37.7567, "centrlon": -122.491, "sqmi": 2.0687, "origin": 7885, "orig_sqmi": 3811.5203}, "geometry": {"type": "Polygon", "coordinates": [[[-122.482187547, 37.746202794], [-122.498490796, 37.744947678], [-122.507309593, 37.755473249], [-122.499825203, 37.767255078], [-122.483518612, 37.768511336], [-122.474699753, 37.757984622], [-122.482187547, 37.746202794]]]}}, {"id": "21", "type": "Feature", "properties": {"name": "87283095bffffff", "id": 608692975869886500, "centrlat": 37.779, "centrlon": -122.4923, "sqmi": 2.0682, "origin": 7757, "orig_sqmi": 3750.6741}, "geometry": {"type": "Polygon", "coordinates": [[[-122.483518612, 37.768511336], [-122.499825203, 37.767255078], [-122.50864595, 37.777778032], [-122.50116017, 37.789558387], [-122.484850236, 37.790815789], [-122.476029426, 37.780291691], [-122.483518612, 37.768511336]]]}}, {"id": "22", "type": "Feature", "properties": {"name": "872830812ffffff", "id": 608692970350182400, "centrlat": 37.82, "centrlon": -122.2488, "sqmi": 2.072, "origin": 7695, "orig_sqmi": 3713.7247}, "geometry": {"type": "Polygon", "coordinates": [[[-122.239947546, 37.809420964], [-122.256289112, 37.808195576], [-122.265102507, 37.818740418], [-122.257574361, 37.830511789], [-122.241229435, 37.8317383], [-122.232416016, 37.821192317], [-122.239947546, 37.809420964]]]}}, {"id": "23", "type": "Feature", "properties": {"name": "87283092bffffff", "id": 608692975064580100, "centrlat": 37.6396, "centrlon": -122.4104, "sqmi": 2.0732, "origin": 7242, "orig_sqmi": 3493.1875}, "geometry": {"type": "Polygon", "coordinates": [[[-122.401568505, 37.629026409], [-122.417862905, 37.62778713], [-122.426668236, 37.638334385], [-122.419179218, 37.650122068], [-122.402881479, 37.651362487], [-122.394076098, 37.640814084], [-122.401568505, 37.629026409]]]}}, {"id": "24", "type": "Feature", "properties": {"name": "872830813ffffff", "id": 608692970366959600, "centrlat": 37.8293, "centrlon": -122.2739, "sqmi": 2.0713, "origin": 7031, "orig_sqmi": 3394.4595}, "geometry": {"type": "Polygon", "coordinates": [[[-122.265102507, 37.818740418], [-122.281442611, 37.817511256], [-122.290257929, 37.828052342], [-122.282733171, 37.839823729], [-122.266389707, 37.841054015], [-122.257574361, 37.830511789], [-122.265102507, 37.818740418]]]}}, {"id": "25", "type": "Feature", "properties": {"name": "872830876ffffff", "id": 608692972027904000, "centrlat": 37.8051, "centrlon": -122.4447, "sqmi": 2.0685, "origin": 6753, "orig_sqmi": 3264.7025}, "geometry": {"type": "Polygon", "coordinates": [[[-122.435907697, 37.794575223], [-122.452223997, 37.793324207], [-122.461044866, 37.803849447], [-122.45354949, 37.815626845], [-122.437229842, 37.816878999], [-122.428408918, 37.806352616], [-122.435907697, 37.794575223]]]}}, {"id": "26", "type": "Feature", "properties": {"name": "872830816ffffff", "id": 608692970417291300, "centrlat": 37.7976, "centrlon": -122.2475, "sqmi": 2.0726, "origin": 6627, "orig_sqmi": 3197.4126}, "geometry": {"type": "Polygon", "coordinates": [[[-122.238666198, 37.787099525], [-122.255004404, 37.78587526], [-122.263815848, 37.796422715], [-122.256289112, 37.808195576], [-122.239947546, 37.809420964], [-122.231136077, 37.798872367], [-122.238666198, 37.787099525]]]}}, {"id": "27", "type": "Feature", "properties": {"name": "872830821ffffff", "id": 608692970601840600, "centrlat": 37.7419, "centrlon": -122.3918, "sqmi": 2.0711, "origin": 6392, "orig_sqmi": 3086.3068}, "geometry": {"type": "Polygon", "coordinates": [[[-122.383013122, 37.731369362], [-122.399325725, 37.730128148], [-122.408138896, 37.740666132], [-122.400639512, 37.752446475], [-122.384323562, 37.753688825], [-122.375510345, 37.743149697], [-122.383013122, 37.731369362]]]}}, {"id": "28", "type": "Feature", "properties": {"name": "87283080cffffff", "id": 608692970249519100, "centrlat": 37.8088, "centrlon": -122.3958, "sqmi": 2.0694, "origin": 6289, "orig_sqmi": 3039.0731}, "geometry": {"type": "Polygon", "coordinates": [[[-122.386946098, 37.798315483], [-122.403268745, 37.797070861], [-122.412087767, 37.807601004], [-122.404584191, 37.81937691], [-122.388258193, 37.820622666], [-122.379439123, 37.810091381], [-122.386946098, 37.798315483]]]}}, {"id": "29", "type": "Feature", "properties": {"name": "87283092affffff", "id": 608692975047802900, "centrlat": 37.6303, "centrlon": -122.3853, "sqmi": 2.0739, "origin": 6118, "orig_sqmi": 2949.9876}, "geometry": {"type": "Polygon", "coordinates": [[[-122.376469182, 37.619710934], [-122.39276507, 37.618475408], [-122.401568505, 37.629026409], [-122.394076098, 37.640814084], [-122.37777687, 37.642050749], [-122.368973389, 37.6314986], [-122.376469182, 37.619710934]]]}}, {"id": "30", "type": "Feature", "properties": {"name": "872834741ffffff", "id": 608693241721651200, "centrlat": 37.4212, "centrlon": -122.1769, "sqmi": 2.0831, "origin": 6113, "orig_sqmi": 2934.6077}, "geometry": {"type": "Polygon", "coordinates": [[[-122.168109217, 37.410615275], [-122.184396731, 37.409416546], [-122.193173253, 37.420012897], [-122.185662276, 37.431809133], [-122.169371423, 37.43300899], [-122.160594888, 37.422411485], [-122.168109217, 37.410615275]]]}}, {"id": "31", "type": "Feature", "properties": {"name": "8728308adffffff", "id": 608692972950650900, "centrlat": 37.8516, "centrlon": -122.2752, "sqmi": 2.0707, "origin": 6071, "orig_sqmi": 2931.7937}, "geometry": {"type": "Polygon", "coordinates": [[[-122.266389707, 37.841054015], [-122.282733171, 37.839823729], [-122.291550441, 37.850362197], [-122.284024275, 37.862132091], [-122.26767745, 37.863363502], [-122.258860152, 37.852823893], [-122.266389707, 37.841054015]]]}}, {"id": "32", "type": "Feature", "properties": {"name": "872830955ffffff", "id": 608692975769223200, "centrlat": 37.7028, "centrlon": -122.4632, "sqmi": 2.0706, "origin": 6056, "orig_sqmi": 2924.7693}, "geometry": {"type": "Polygon", "coordinates": [[[-122.454416009, 37.692287984], [-122.470714088, 37.691038912], [-122.479527097, 37.701573461], [-122.472042085, 37.713358227], [-122.455740665, 37.714608441], [-122.446927599, 37.704072747], [-122.454416009, 37.692287984]]]}}, {"id": "33", "type": "Feature", "properties": {"name": "872830359ffffff", "id": 608692950066528300, "centrlat": 38.4528, "centrlon": -122.7307, "sqmi": 2.0467, "origin": 5988, "orig_sqmi": 2925.7127}, "geometry": {"type": "Polygon", "coordinates": [[[-122.721848327, 38.442379666], [-122.738233113, 38.441062311], [-122.747121996, 38.451483145], [-122.739626194, 38.463222454], [-122.723238035, 38.46454095], [-122.714349052, 38.454118995], [-122.721848327, 38.442379666]]]}}, {"id": "34", "type": "Feature", "properties": {"name": "872834296ffffff", "id": 608693221672878100, "centrlat": 37.4848, "centrlon": -122.2296, "sqmi": 2.0805, "origin": 5740, "orig_sqmi": 2758.9399}, "geometry": {"type": "Polygon", "coordinates": [[[-122.220783821, 37.474171683], [-122.23707514, 37.472963201], [-122.245859371, 37.483546964], [-122.238352305, 37.495340361], [-122.222057646, 37.496549974], [-122.213273394, 37.485965059], [-122.220783821, 37.474171683]]]}}, {"id": "35", "type": "Feature", "properties": {"name": "872830981ffffff", "id": 608692976507420700, "centrlat": 37.7343, "centrlon": -122.1946, "sqmi": 2.0752, "origin": 5574, "orig_sqmi": 2686.0034}, "geometry": {"type": "Polygon", "coordinates": [[[-122.185828469, 37.723760492], [-122.202162858, 37.722546013], [-122.210966553, 37.733106183], [-122.203435875, 37.744881976], [-122.187098127, 37.746097576], [-122.178294417, 37.735536262], [-122.185828469, 37.723760492]]]}}, {"id": "36", "type": "Feature", "properties": {"name": "872834731ffffff", "id": 608693241453215700, "centrlat": 37.3139, "centrlon": -121.9501, "sqmi": 2.0901, "origin": 5533, "orig_sqmi": 2647.2301}, "geometry": {"type": "Polygon", "coordinates": [[[-121.94134213, 37.303270151], [-121.957638908, 37.302106249], [-121.966396086, 37.312738561], [-121.958856465, 37.324535931], [-121.942556341, 37.325700946], [-121.933799185, 37.315067478], [-121.94134213, 37.303270151]]]}}, {"id": "37", "type": "Feature", "properties": {"name": "872830c65ffffff", "id": 608692988922560500, "centrlat": 37.9015, "centrlon": -122.0562, "sqmi": 2.0738, "origin": 5509, "orig_sqmi": 2656.4208}, "geometry": {"type": "Polygon", "coordinates": [[[-122.047412325, 37.890938086], [-122.063788955, 37.889735138], [-122.072600486, 37.900291715], [-122.065035382, 37.912052379], [-122.048655373, 37.913256432], [-122.039843848, 37.902698717], [-122.047412325, 37.890938086]]]}}, {"id": "38", "type": "Feature", "properties": {"name": "87283081effffff", "id": 608692970551509000, "centrlat": 37.8386, "centrlon": -122.2991, "sqmi": 2.0706, "origin": 5491, "orig_sqmi": 2651.9029}, "geometry": {"type": "Polygon", "coordinates": [[[-122.290257929, 37.828052342], [-122.306596566, 37.826819407], [-122.315413803, 37.837356735], [-122.307892437, 37.849128137], [-122.291550441, 37.850362197], [-122.282733171, 37.839823729], [-122.290257929, 37.828052342]]]}}, {"id": "39", "type": "Feature", "properties": {"name": "87283098bffffff", "id": 608692976675192800, "centrlat": 37.7883, "centrlon": -122.2223, "sqmi": 2.0733, "origin": 5437, "orig_sqmi": 2622.339}, "geometry": {"type": "Polygon", "coordinates": [[[-122.213517018, 37.77776881], [-122.229856678, 37.776548317], [-122.238666198, 37.787099525], [-122.231136077, 37.798872367], [-122.214793057, 37.800093982], [-122.205983518, 37.789541632], [-122.213517018, 37.77776881]]]}}, {"id": "40", "type": "Feature", "properties": {"name": "872834743ffffff", "id": 608693241755205600, "centrlat": 37.4342, "centrlon": -122.1531, "sqmi": 2.0832, "origin": 5418, "orig_sqmi": 2600.7593}, "geometry": {"type": "Polygon", "coordinates": [[[-122.144302607, 37.423607595], [-122.160594888, 37.422411485], [-122.169371423, 37.43300899], [-122.161855689, 37.44480376], [-122.145560067, 37.446000997], [-122.136783522, 37.435402338], [-122.144302607, 37.423607595]]]}}, {"id": "41", "type": "Feature", "properties": {"name": "872834702ffffff", "id": 608693240664686600, "centrlat": 37.3588, "centrlon": -121.9525, "sqmi": 2.089, "origin": 5298, "orig_sqmi": 2536.1432}, "geometry": {"type": "Polygon", "coordinates": [[[-121.943771062, 37.348127759], [-121.960074534, 37.346961631], [-121.968835571, 37.357588846], [-121.961293115, 37.369383343], [-121.944986294, 37.370550583], [-121.93622528, 

In [50]:
saved = to_snakecase(gpd.read_file("./saved-selection-geo-stm-scag-top50-origins_h3z7.geojson"))

In [52]:
# saved

##### Checking to see if geonames match

In [21]:
shps[shps['id']==608718595349807100]

,name,id,centrlat,centrlon,sqmi,origin,orig_sqmi,geometry
0,8729a565bffffff,608718595349807100,33.9337,-118.4119,2.2254,52256,23481.8963,"POLYGON ((-118.40364 33.92238, -118.41978 33.9..."

#### Check Trips Data

In [17]:
df = to_snakecase(pd.read_csv(f"{gcs_path}{origins_name}"))

In [18]:
df.sample()

,activity_id,origin_bgrp_2020,origin_trct_2020,origin_cty_2020,origin_st_2020,destination_bgrp_2020,destination_trct_2020,destination_cty_2020,destination_st_2020,primary_mode,trip_purpose,previous_trip_purpose,trip_start_time,trip_end_time,trip_duration_minutes,trip_distance_miles,vehicle_type,vehicle_fuel_type,transit_submode,transit_agency,transit_route,origin_land_use,origin_building_use,destination_land_use,destination_building_use,trip_taker_person_id,trip_taker_household_id,trip_taker_age,trip_taker_sex,trip_taker_race_ethnicity,trip_taker_employment_status,trip_taker_wfh,trip_taker_individual_income,trip_taker_commute_mode,trip_taker_household_size,trip_taker_household_income,trip_taker_available_vehicles,trip_taker_resident_type,trip_taker_industry,trip_taker_building_type,trip_taker_school_grade_attending,trip_taker_education,trip_taker_tenure,trip_taker_language,trip_taker_home_bgrp_2020,trip_taker_home_trct_2020,trip_taker_home_cty_2020,trip_taker_home_st_2020,trip_taker_work_bgrp_2020,trip_taker_work_trct_2020,trip_taker_work_cty_2020,trip_taker_work_st_2020,origin_custom,destination_custom,tour_type,trip_start_local_hour,trip_end_local_hour,origin_custom_id,destination_custom_id,origin_zcta_2020,destination_zcta_2020,destination_custom_lat,destination_custom_lng,origin_custom_lng,origin_custom_lat
236186,18333842258138891537,"2 (Tract 2653.01, Los Angeles, CA)","2653.01 (Los Angeles, CA)","Los Angeles County, CA",California,"4 (Tract 320.02, Orange, CA)","320.02 (Orange, CA)","Orange County, CA",California,private_auto,home,work,14:28:00,16:11:12,103,54.0,NaN,NaN,NaN,NaN,NaN,education,education,single_family,single_family,1894194950998001667,17575166101483736090,51.0,female,white_not_hispanic_or_latino,employed,in_person,81142.0,private_auto,3,255020.0,three_plus,core,naics61,single_family,not_attending_school,bachelors_degree,owner,english,"4 (Tract 320.02, Orange, CA)","320.02 (Orange, CA)","Orange County, CA",California,"2 (Tract 2653.01, Los Angeles, CA)","2653.01 (Los Angeles, CA)","Los Angeles County, CA",California,8729a199dffffff,NaN,commute,14,16,608718334464098300,NaN,90095,92691,NaN,NaN,-118.4387,34.0603

In [19]:
df.origin_custom_id.value_counts()

origin_custom_id
608718595349807100    52256
608718350972878800    38886
608718350654111700    29935
608718334464098300    26434
608718350670889000    23046
608718350788329500    19634
608718334682202100    17933
608718350838661100    16634
608718334212440000    16107
608718334480875500    15325
608718333994336300    15238
608718588957687800    15061
608718334447321100    15019
608718334849974300    14666
608718350721220600    14614
608718350167572500    14582
608718350905770000    14525
608718594158624800    14431
608718350687666200    14302
608718272824606700    13977
608718334413766700    13532
608718345268625400    13164
608718350637334500    12771
608718595333029900    12770
608718329984581600    12712
608718350888992800    12047
608718334782865400    11822
608718334027890700    11485
608718350620557300    10713
608718334178885600    10570
608718350754775000    10452
608718597463736300    10025
608718334011113500     9690
608718237978329100     9663
608718595400138800     9538
608718345302179800     9481
608718331393867800     9298
608718597212078100     8938
608718350855438300     8872
608718594192179200     8820
608718346409476100     8810
608718334044667900     8614
608718350771552300     8607
608718226402050000     8560
608718350486339600     8488
608718597765726200     8393
608719708585197600     8387
608718350821883900     8308
608718646788751400     8301
608718350805106700     8296
Name: count, dtype: int64