# Grouping Locations for Origins and Destinations

In [1]:
import gcsfs as fs
import geopandas as gpd
import numpy as np
import pandas as pd
from calitp_data_analysis import get_fs, utils
from calitp_data_analysis.sql import to_snakecase
from siuba import *

fs = get_fs()

In [2]:
import altair as alt
import folium
from IPython.display import HTML
from calitp_data_analysis import calitp_color_palette as cp

In [3]:
import _location_utils

In [4]:
gcs_path = "gs://calitp-analytics-data/data-analyses/big_data/STM/origins/"

In [5]:
with get_fs().open(f"{gcs_path}replica-stm_origin_la-03_18_26-destination_layer.zip") as f:
        dest = to_snakecase(gpd.read_file(f))

In [6]:
# with get_fs().open(f"{gcs_path}replica-stm_pois-02_05_26-origin_layer.zip") as f:
#         origins = to_snakecase(gpd.read_file(f))

In [7]:
dest.sample()

,geoname,customgeo,centrlat,centrlon,sqmi,destin,dest_sqmi,geometry
3078,872832b15ffffff,608693120724369400,38.5584,-121.4715,2.0684,5,2.4173,"POLYGON ((-121.46267 38.54782, -121.47922 38.5..."

In [7]:
# top20_dest = (dest.sort_values(by='tripsbydestination', ascending=False)).head(20)

In [8]:
# top20_dest

,geoname,customgeoid,centroidlat,centroidlon,squaremiles,tripsbydestination,tripsbydestination_sqmi,geometry
0,"67 (Clark, NV)",32003006700,36.1138,-115.1704,1.8209,319815,175633.7235,"POLYGON ((-115.18048 36.10070, -115.18033 36.1..."
1,"9800.28 (Los Angeles, CA)",6037980028,33.9398,-118.4135,7.6039,262877,34571.4831,"POLYGON ((-118.45233 33.94300, -118.43712 33.9..."
2,"68 (Clark, NV)",32003006800,36.0850,-115.1539,5.9595,248569,41709.9095,"POLYGON ((-115.18056 36.07095, -115.18027 36.0..."
3,"85.11 (San Diego, CA)",6073008511,32.8260,-117.1416,5.8790,243134,41356.1186,"POLYGON ((-117.17786 32.84732, -117.17781 32.8..."
4,"626.10 (Orange, CA)",6059062610,33.6692,-117.8604,4.5719,222922,48758.9693,"POLYGON ((-117.88794 33.67191, -117.88777 33.6..."
5,"755.16 (Orange, CA)",6059075516,33.6930,-117.8450,3.9135,189510,48424.6462,"POLYGON ((-117.87211 33.68726, -117.87076 33.6..."
6,"9800.35 (Los Angeles, CA)",6037980035,34.0124,-117.9434,6.1586,154024,25009.5085,"POLYGON ((-117.99807 34.02957, -117.99723 34.0..."
7,"4415.03 (Alameda, CA)",6001441503,37.5048,-122.0331,32.9077,150111,4561.5714,"POLYGON ((-122.13577 37.55885, -122.12858 37.5..."
8,"5050.06 (Santa Clara, CA)",6085505006,37.3936,-121.9211,5.4989,145079,26383.2900,"POLYGON ((-121.94173 37.37665, -121.94167 37.3..."
9,"78 (San Bernardino, CA)",6071007800,34.0734,-117.2192,6.9204,141267,20413.0293,"POLYGON ((-117.24393 34.08739, -117.24380 34.0..."
10,"5052.02 (Santa Clara, CA)",6085505202,37.3703,-121.9607,3.5366,129935,36739.6174,"POLYGON ((-121.98730 37.37044, -121.98696 37.3..."
11,"93.07 (San Diego, CA)",6073009307,32.7744,-117.1351,1.7716,129005,72818.0252,"POLYGON ((-117.16352 32.76263, -117.16351 32.7..."
12,"9843 (San Mateo, CA)",6081984300,37.6208,-122.3785,4.4490,128652,28916.9407,"POLYGON ((-122.40369 37.63498, -122.40368 37.6..."
13,"626.14 (Orange, CA)",6059062614,33.6426,-117.8418,2.4213,126766,52354.8299,"POLYGON ((-117.86155 33.65117, -117.86147 33.6..."
14,"117 (San Francisco, CA)",6075011700,37.7905,-122.4035,0.2130,124764,585866.1893,"POLYGON ((-122.40872 37.78985, -122.40869 37.7..."
15,"2653.01 (Los Angeles, CA)",6037265301,34.0711,-118.4454,0.6163,118845,192832.8583,"POLYGON ((-118.45544 34.07529, -118.45516 34.0..."
16,"6023 (San Mateo, CA)",6081602300,37.6514,-122.3955,5.1697,115476,22337.0267,"POLYGON ((-122.43443 37.65508, -122.43422 37.6..."
17,"31.11 (Washoe, NV)",32031003111,39.5305,-119.7190,7.8852,115155,14603.9758,"POLYGON ((-119.78082 39.53511, -119.78067 39.5..."
18,"525.18 (Orange, CA)",6059052518,33.6594,-117.7579,2.2431,113662,50672.1698,"POLYGON ((-117.77786 33.65748, -117.77608 33.6..."
19,"83.05 (San Diego, CA)",6073008305,32.8798,-117.2318,1.7214,113008,65648.8157,"POLYGON ((-117.24389 32.87796, -117.24387 32.8..."

In [9]:
# (dest.head(20)).explore()

In [10]:
# top20_dest['dest_name_long'] = top20_dest['geoname'].str.split('(').str[1]
# top20_dest['dest_code'] = top20_dest['geoname'].str.split('(').str[0]

In [11]:
# top20_dest['dest_name_long'] = top20_dest['dest_name_long'].str.replace(')', '')

/tmp/ipykernel_931/3533316647.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  top20_dest['dest_name_long'] = top20_dest['dest_name_long'].str.replace(')', '')

In [12]:
# top20_dest['dest_name_short'] = top20_dest['dest_name_long'].str.split(',').str[0]

In [13]:
# top20_dest['dest_name'] = top20_dest["dest_name_short"] + "_" + top20_dest['dest_code']

In [14]:
# top20_dest['dest_name'] = top20_dest['dest_name'].str.replace(' ', '')

In [15]:
# dest_list = top20_dest['dest_name'].to_list()

In [16]:
### hashing out after running 
### we dont need this for the analysis since we are looking at all trips
# _location_utils.aggregate_destination_station_geometries(top20_dest, dest_list, "dest_name")

In [18]:
origin_la_980028 = to_snakecase(pd.read_csv(f"{gcs_path}origins/replica-stm_origin_la_980028-02_06_26-trips_dataset.csv"))

/tmp/ipykernel_931/334489282.py:1: DtypeWarning: Columns (18,19,20,25,26,28,29,30,31,33,36,38,39,40,41,42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  origin_la_980028 = to_snakecase(pd.read_csv(f"{gcs_path}origins/replica-stm_origin_la_980028-02_06_26-trips_dataset.csv"))

In [22]:
origin_la_980028.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260992 entries, 0 to 260991
Data columns (total 52 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   activity_id                        260992 non-null  uint64
 1   origin_bgrp_2020                   260992 non-null  object
 2   origin_trct_2020                   260992 non-null  object
 3   origin_cty_2020                    260992 non-null  object
 4   origin_st_2020                     260992 non-null  object
 5   destination_bgrp_2020              260992 non-null  object
 6   destination_trct_2020              260992 non-null  object
 7   destination_cty_2020               260992 non-null  object
 8   destination_st_2020                260992 non-null  object
 9   primary_mode                       260992 non-null  object
 10  trip_purpose                       260992 non-null  object
 11  previous_trip_purpose              260992 non-null  object
 12  trip_start_time                    260992 non-null  object
 13  trip_end_time                      260992 non-null  object
 14  trip_duration_minutes              260992 non-null  int64
 15  trip_distance_miles                260992 non-null  float64
 16  vehicle_type                       220935 non-null  object
 17  vehicle_fuel_type                  239785 non-null  object
 18  transit_submode                    3124 non-null    object
 19  transit_agency                     3124 non-null    object
 20  transit_route                      3124 non-null    object
 21  origin_land_use                    260992 non-null  object
 22  origin_building_use                260992 non-null  object
 23  destination_land_use               260992 non-null  object
 24  destination_building_use           260992 non-null  object
 25  trip_taker_person_id               260992 non-null  object
 26  trip_taker_household_id            229376 non-null  object
 27  trip_taker_age                     176285 non-null  float64
 28  trip_taker_sex                     176285 non-null  object
 29  trip_taker_race_ethnicity          176285 non-null  object
 30  trip_taker_employment_status       176285 non-null  object
 31  trip_taker_wfh                     176285 non-null  object
 32  trip_taker_individual_income       176285 non-null  float64
 33  trip_taker_commute_mode            176285 non-null  object
 34  trip_taker_household_size          260992 non-null  int64
 35  trip_taker_household_income        176285 non-null  float64
 36  trip_taker_available_vehicles      176285 non-null  object
 37  trip_taker_resident_type           253367 non-null  object
 38  trip_taker_industry                176285 non-null  object
 39  trip_taker_building_type           176285 non-null  object
 40  trip_taker_school_grade_attending  176285 non-null  object
 41  trip_taker_education               176285 non-null  object
 42  trip_taker_tenure                  176285 non-null  object
 43  trip_taker_language                176285 non-null  object
 44  trip_taker_home_bgrp_2020          253367 non-null  object
 45  trip_taker_home_trct_2020          253367 non-null  object
 46  trip_taker_home_cty_2020           253367 non-null  object
 47  trip_taker_home_st_2020            253367 non-null  object
 48  trip_taker_work_bgrp_2020          253367 non-null  object
 49  trip_taker_work_trct_2020          253367 non-null  object
 50  trip_taker_work_cty_2020           253367 non-null  object
 51  trip_taker_work_st_2020            253367 non-null  object
dtypes: float64(4), int64(2), object(45), uint64(1)
memory usage: 103.5+ MB